//! Oracle test framework for validating ferrolearn against scikit-learn fixtures.
//!
//! Loads JSON fixtures generated by `scripts/generate_sklearn_fixtures.py`,
//! parses input / parameter / expected blocks into `ndarray` arrays, and compares
//! outputs using algorithm-class-aware relative+absolute tolerances.
//!
//! # Fixture schema (v2)
//!
//! ```json
//! {
//!   "description": "...",
//!   "sklearn_version": "1.7.2",
//!   "sklearn_pin": "scikit-learn==1.7.2",
//!   "random_state": 42,
//!   "input": { "X": [[...]], "y": [...] },
//!   "params": { "fit_intercept": true },
//!   "expected": { "coefficients": [...], "intercept": 0.123, "predictions": [...] },
//!   "tolerance": { "rel": 1e-6, "abs": 1e-9 },
//!   "divergence_id": null
//! }
//! ```
//!
//! Schema v1 fixtures (no `tolerance` / `sklearn_pin` / `divergence_id` fields)
//! continue to work — defaults are applied.

#![allow(clippy::missing_panics_doc, clippy::missing_errors_doc)]

use ndarray::{Array1, Array2};
use serde::Deserialize;
use std::path::{Path, PathBuf};

// Re-export so consumers don't need their own serde_json dependency.
pub use serde_json;

// ---------------------------------------------------------------------------
// Tolerance constants, indexed by algorithm class.
//
// Each constant pair (REL, ABS) is the default tolerance for an algorithm
// class when no per-fixture override is present. The composite assertion is
// `|actual - expected| <= max(abs, rel * |expected|)`, which behaves as
// `abs` near zero and as `rel * expected` for large magnitudes.
// ---------------------------------------------------------------------------

/// Direct linear solves (LinearRegression via OLS, Ridge closed-form).
///
/// These are essentially deterministic linear algebra — sklearn and
/// ferrolearn both reduce to LAPACK gels / cholesky and should agree to
/// ~1e-9. Tightened from the old per-test 1e-6 to catch real drift.
pub const TOL_LINEAR_FIT_REL: f64 = 1e-9;
pub const TOL_LINEAR_FIT_ABS: f64 = 1e-12;

/// Iterative linear solvers (Lasso, ElasticNet via coordinate descent).
///
/// Convergence-dependent. Both libraries use coordinate descent but with
/// slightly different update orderings; setting this tighter than sklearn's
/// own default `tol=1e-4` would be stricter than sklearn itself, so 1e-4
/// (rel and abs) is the floor — and ABS must be at least 1e-4 so small
/// coefficients / predictions still fit inside the tol-bounded envelope
/// (otherwise `max(abs, rel*|expected|)` collapses to ~|expected|*1e-4
/// for predictions in the 0.1–1.0 range, below the actual coordinate-
/// descent path divergence).
pub const TOL_ITERATIVE_LINEAR_REL: f64 = 1e-4;
pub const TOL_ITERATIVE_LINEAR_ABS: f64 = 1e-4;

/// Logistic regression and other gradient-based classifiers (LBFGS / Newton-CG).
///
/// ferrolearn's L-BFGS converges to a slightly different optimum than
/// sklearn's when problems are well-conditioned — both are within their
/// own stopping tolerance. Probability agreement to 1e-3 rel; labels via
/// accuracy floor (see `MIN_LOGISTIC_ACCURACY`).
pub const TOL_LOGISTIC_REL: f64 = 1e-3;
pub const TOL_LOGISTIC_ABS: f64 = 1e-6;

/// Floor for label-agreement rate between ferrolearn's LogisticRegression
/// and sklearn's on the same fixture. 0.97 keeps a tight gate while
/// allowing a handful of borderline samples (|p - 0.5| small) to flip
/// when the converged probabilities differ in the last few digits.
pub const MIN_LOGISTIC_ACCURACY: f64 = 0.97;

/// Tree fits — predictions on training data should be bit-exact for ID-style
/// splits when the same algorithm + seed is used. Tree structure itself is
/// not directly comparable because tie-breaking on identical impurity gains
/// can produce different (but equivalent) trees; we compare *predictions*
/// with a tight tolerance instead.
pub const TOL_TREE_PRED_REL: f64 = 1e-9;
pub const TOL_TREE_PRED_ABS: f64 = 1e-12;

/// Tree ensembles (RandomForest, GradientBoosting) — averaging over many trees
/// dampens individual tree differences but seed sensitivity remains.
pub const TOL_TREE_ENSEMBLE_REL: f64 = 1e-6;
pub const TOL_TREE_ENSEMBLE_ABS: f64 = 1e-9;

/// Distance-based predictors (KNN regression/classification). With identical
/// metrics and tie-breaking they should match exactly; the small budget is
/// for numerical noise in distance accumulation on large feature counts.
pub const TOL_NEIGHBORS_REL: f64 = 1e-9;
pub const TOL_NEIGHBORS_ABS: f64 = 1e-12;

/// Naive Bayes — closed-form parameter estimates; should be tight.
pub const TOL_NAIVE_BAYES_REL: f64 = 1e-9;
pub const TOL_NAIVE_BAYES_ABS: f64 = 1e-12;

/// Clustering (KMeans, DBSCAN, etc.). Label permutation is handled separately
/// by comparing via ARI (Adjusted Rand Index) when raw labels disagree.
/// Cluster *centers* are compared with this tolerance.
pub const TOL_CLUSTER_CENTER_REL: f64 = 1e-4;
pub const TOL_CLUSTER_CENTER_ABS: f64 = 1e-6;

/// Cluster assignment quality threshold: ARI between ferrolearn and sklearn
/// must exceed this on the same input. 1.0 = perfect parity (after
/// label permutation), 0.95 is the floor for "effectively identical".
pub const MIN_CLUSTER_ARI: f64 = 0.95;

/// Decomposition (PCA, NMF, ICA). PCA components are sign-ambiguous; the
/// comparison must compare absolute values component-wise.
pub const TOL_DECOMP_REL: f64 = 1e-6;
pub const TOL_DECOMP_ABS: f64 = 1e-9;

/// Preprocessing (scalers, encoders). Deterministic linear operations —
/// should be near bit-exact.
pub const TOL_PREPROCESS_REL: f64 = 1e-10;
pub const TOL_PREPROCESS_ABS: f64 = 1e-13;

/// Metrics (accuracy, MSE, R², AUC, log_loss). Closed-form reductions.
pub const TOL_METRIC_REL: f64 = 1e-9;
pub const TOL_METRIC_ABS: f64 = 1e-12;

/// Kernel methods (KernelRidge, SVM). Slightly looser due to iterative
/// QP solvers and kernel matrix conditioning.
pub const TOL_KERNEL_REL: f64 = 1e-5;
pub const TOL_KERNEL_ABS: f64 = 1e-8;

/// Covariance estimators (EmpiricalCovariance, LedoitWolf, OAS, MinCovDet).
pub const TOL_COVARIANCE_REL: f64 = 1e-7;
pub const TOL_COVARIANCE_ABS: f64 = 1e-10;

/// Neural (MLP, BernoulliRBM). Highly seed-sensitive; the tolerance is
/// applied to a metric (final loss, accuracy) rather than parameters.
pub const TOL_NEURAL_REL: f64 = 1e-2;
pub const TOL_NEURAL_ABS: f64 = 1e-4;

/// Model selection (KFold splits, cross_val_score). Splits must match
/// exactly when `random_state` is identical; scores match within metric
/// tolerance.
pub const TOL_MODEL_SEL_REL: f64 = 1e-9;
pub const TOL_MODEL_SEL_ABS: f64 = 1e-12;

/// Numerical routines (interpolation, root finding).
pub const TOL_NUMERICAL_REL: f64 = 1e-9;
pub const TOL_NUMERICAL_ABS: f64 = 1e-12;

// ---------------------------------------------------------------------------
// Composite assertion helpers — relative + absolute tolerance.
//
// Threshold = max(tol_abs, tol_rel * |expected|).
// This is the same shape as numpy.testing.assert_allclose.
// ---------------------------------------------------------------------------

/// Assert two scalars agree within (rel, abs) tolerance.
///
/// NaN matches NaN. Infinity must match sign.
///
/// # Panics
/// Panics with a diagnostic message when the values differ by more than the
/// composite tolerance.
pub fn assert_close(actual: f64, expected: f64, rel: f64, abs: f64, label: &str) {
    if actual.is_nan() && expected.is_nan() {
        return;
    }
    assert!(
        actual.is_nan() == expected.is_nan(),
        "{label}: NaN mismatch (actual={actual}, expected={expected})"
    );
    if actual.is_infinite() && expected.is_infinite() {
        assert_eq!(
            actual.is_sign_positive(),
            expected.is_sign_positive(),
            "{label}: infinity sign mismatch (actual={actual}, expected={expected})"
        );
        return;
    }
    let threshold = abs.max(rel * expected.abs());
    let diff = (actual - expected).abs();
    assert!(
        diff <= threshold,
        "{label}: actual={actual} expected={expected} diff={diff:.3e} \
         threshold={threshold:.3e} (rel={rel:.1e}, abs={abs:.1e})"
    );
}

/// Assert that two slices agree element-by-element within (rel, abs) tolerance.
///
/// Reports the first failing index. Length mismatches are a hard failure.
pub fn assert_close_slice(actual: &[f64], expected: &[f64], rel: f64, abs: f64, label: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: length mismatch ({} vs {})",
        actual.len(),
        expected.len()
    );
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_close(a, e, rel, abs, &format!("{label}[{i}]"));
    }
}

/// Compare two slices treating sign as ambiguous (for PCA / ICA components
/// where the sign of each row is not uniquely determined).
///
/// For each pair, accepts either `|actual[i] - expected[i]| <= tol` OR
/// `|actual[i] + expected[i]| <= tol`. This is a common-enough pattern for
/// decomposition methods that we lift it into the oracle.
pub fn assert_close_slice_sign_ambiguous(
    actual: &[f64],
    expected: &[f64],
    rel: f64,
    abs: f64,
    label: &str,
) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: length mismatch ({} vs {})",
        actual.len(),
        expected.len()
    );
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        let threshold = abs.max(rel * e.abs());
        let diff_pos = (a - e).abs();
        let diff_neg = (a + e).abs();
        let diff = diff_pos.min(diff_neg);
        assert!(
            diff <= threshold,
            "{label}[{i}]: actual={a} expected={e} (or its negation) \
             min_diff={diff:.3e} threshold={threshold:.3e}"
        );
    }
}

/// Per-row sign-flip-aware comparison for 2D arrays (PCA components_, ICA mixing).
///
/// Tries both signs for each row and chooses the one that minimizes the
/// row's L∞ error. Both libraries must produce the same components up to
/// row sign.
pub fn assert_close_rows_sign_ambiguous(
    actual: &Array2<f64>,
    expected: &Array2<f64>,
    rel: f64,
    abs: f64,
    label: &str,
) {
    assert_eq!(
        actual.shape(),
        expected.shape(),
        "{label}: shape mismatch ({:?} vs {:?})",
        actual.shape(),
        expected.shape()
    );
    for (i, (a_row, e_row)) in actual.rows().into_iter().zip(expected.rows()).enumerate() {
        let pos_max: f64 = a_row
            .iter()
            .zip(e_row.iter())
            .map(|(&a, &e)| (a - e).abs())
            .fold(0.0f64, f64::max);
        let neg_max: f64 = a_row
            .iter()
            .zip(e_row.iter())
            .map(|(&a, &e)| (a + e).abs())
            .fold(0.0f64, f64::max);
        let use_pos = pos_max <= neg_max;
        for (j, (&a, &e)) in a_row.iter().zip(e_row.iter()).enumerate() {
            let threshold = abs.max(rel * e.abs());
            let diff = if use_pos { (a - e).abs() } else { (a + e).abs() };
            assert!(
                diff <= threshold,
                "{label}[row {i}, col {j}]: actual={a} expected={e} \
                 (sign {sign}) diff={diff:.3e} threshold={threshold:.3e}",
                sign = if use_pos { "+" } else { "-" }
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Discrete (label) comparison helpers — exact equality and ARI.
// ---------------------------------------------------------------------------

/// Strict equality of integer label slices. Used for classifier predictions
/// where any divergence is a real disagreement.
pub fn assert_labels_equal(actual: &[i64], expected: &[i64], label: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: length mismatch ({} vs {})",
        actual.len(),
        expected.len()
    );
    let mut mismatches = 0usize;
    let mut first = None;
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        if a != e {
            mismatches += 1;
            if first.is_none() {
                first = Some((i, a, e));
            }
        }
    }
    if mismatches > 0 {
        let (idx, a, e) = first.unwrap();
        panic!(
            "{label}: {mismatches}/{} label mismatches (first at index {idx}: \
             actual={a}, expected={e})",
            actual.len()
        );
    }
}

/// Adjusted Rand Index between two integer clusterings.
///
/// 1.0 = identical clustering up to label permutation, 0.0 = independent,
/// can go slightly negative.
///
/// Used to compare ferrolearn cluster labels against sklearn's when raw
/// labels diverge only by permutation.
#[must_use]
pub fn adjusted_rand_index(a: &[i64], b: &[i64]) -> f64 {
    assert_eq!(a.len(), b.len(), "ARI: label arrays must be the same length");
    let n = a.len();
    if n == 0 {
        return 1.0;
    }
    // Build contingency table.
    let mut classes_a: Vec<i64> = a.to_vec();
    classes_a.sort_unstable();
    classes_a.dedup();
    let mut classes_b: Vec<i64> = b.to_vec();
    classes_b.sort_unstable();
    classes_b.dedup();
    let idx_a = |x: i64| classes_a.iter().position(|&v| v == x).unwrap();
    let idx_b = |x: i64| classes_b.iter().position(|&v| v == x).unwrap();
    let mut cont = vec![vec![0u64; classes_b.len()]; classes_a.len()];
    for (&x, &y) in a.iter().zip(b.iter()) {
        cont[idx_a(x)][idx_b(y)] += 1;
    }
    // Sums.
    let row_sums: Vec<u64> = cont.iter().map(|r| r.iter().sum()).collect();
    let col_sums: Vec<u64> = (0..classes_b.len())
        .map(|j| cont.iter().map(|r| r[j]).sum())
        .collect();
    let comb2 = |k: u64| if k < 2 { 0u128 } else { u128::from(k) * (u128::from(k) - 1) / 2 };
    let sum_comb_cont: u128 = cont
        .iter()
        .flat_map(|r| r.iter())
        .map(|&v| comb2(v))
        .sum();
    let sum_comb_row: u128 = row_sums.iter().map(|&v| comb2(v)).sum();
    let sum_comb_col: u128 = col_sums.iter().map(|&v| comb2(v)).sum();
    let total = comb2(n as u64);
    if total == 0 {
        return 1.0;
    }
    let expected_index = (sum_comb_row as f64) * (sum_comb_col as f64) / (total as f64);
    let max_index = ((sum_comb_row + sum_comb_col) as f64) / 2.0;
    let observed_index = sum_comb_cont as f64;
    if (max_index - expected_index).abs() < f64::EPSILON {
        return 1.0;
    }
    (observed_index - expected_index) / (max_index - expected_index)
}

/// Assert that two cluster label arrays agree up to permutation (ARI >= min).
pub fn assert_ari_ge(actual: &[i64], expected: &[i64], min_ari: f64, label: &str) {
    let ari = adjusted_rand_index(actual, expected);
    assert!(
        ari >= min_ari,
        "{label}: ARI {ari:.4} below minimum {min_ari:.4} \
         (n={n}, sklearn-divergence may indicate a real bug)",
        n = actual.len()
    );
}

// ---------------------------------------------------------------------------
// JSON parsers — work directly off serde_json::Value.
// ---------------------------------------------------------------------------

/// Parse a JSON nested array `[[...], [...], ...]` into an `Array2<f64>`.
#[must_use]
pub fn json_to_array2(value: &serde_json::Value) -> Array2<f64> {
    let rows: Vec<Vec<f64>> = value
        .as_array()
        .expect("expected JSON array of rows")
        .iter()
        .map(|row| {
            row.as_array()
                .expect("expected JSON array of row values")
                .iter()
                .map(parse_f64_value)
                .collect()
        })
        .collect();
    if rows.is_empty() {
        return Array2::zeros((0, 0));
    }
    let n_rows = rows.len();
    let n_cols = rows[0].len();
    let flat: Vec<f64> = rows.into_iter().flatten().collect();
    Array2::from_shape_vec((n_rows, n_cols), flat).expect("uniform row lengths")
}

/// Parse a JSON flat array `[a, b, c]` into an `Array1<f64>`.
#[must_use]
pub fn json_to_array1(value: &serde_json::Value) -> Array1<f64> {
    let vec: Vec<f64> = value
        .as_array()
        .expect("expected JSON array")
        .iter()
        .map(parse_f64_value)
        .collect();
    Array1::from_vec(vec)
}

/// Parse a JSON flat array of integers into a `Vec<i64>`.
#[must_use]
pub fn json_to_labels(value: &serde_json::Value) -> Vec<i64> {
    value
        .as_array()
        .expect("expected JSON array of labels")
        .iter()
        .map(|v| {
            v.as_i64().unwrap_or_else(|| {
                v.as_f64().map(|x| x as i64).unwrap_or_else(|| {
                    panic!("label must be int or float-int, got {v}")
                })
            })
        })
        .collect()
}

/// Parse a JSON flat array of usize counts.
#[must_use]
pub fn json_to_usize(value: &serde_json::Value) -> Vec<usize> {
    value
        .as_array()
        .expect("expected JSON array")
        .iter()
        .map(|v| v.as_u64().expect("expected non-negative integer") as usize)
        .collect()
}

/// Parse a single JSON value to f64. Accepts numeric literals and the
/// string sentinels "NaN", "Infinity", "-Infinity".
#[must_use]
pub fn parse_f64_value(v: &serde_json::Value) -> f64 {
    match v {
        serde_json::Value::Number(n) => n.as_f64().expect("number must fit in f64"),
        serde_json::Value::String(s) => match s.as_str() {
            "NaN" => f64::NAN,
            "Infinity" | "Inf" => f64::INFINITY,
            "-Infinity" | "-Inf" => f64::NEG_INFINITY,
            other => other
                .parse::<f64>()
                .unwrap_or_else(|_| panic!("cannot parse '{other}' as f64")),
        },
        _ => panic!("unexpected JSON value for f64: {v}"),
    }
}

// ---------------------------------------------------------------------------
// Fixture loading.
// ---------------------------------------------------------------------------

/// Parsed fixture file (schema v2 with v1 backwards compatibility).
#[derive(Debug, Deserialize)]
pub struct Fixture {
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub sklearn_version: Option<String>,
    #[serde(default)]
    pub sklearn_pin: Option<String>,
    #[serde(default)]
    pub random_state: Option<u64>,
    pub input: serde_json::Value,
    #[serde(default)]
    pub params: serde_json::Value,
    pub expected: serde_json::Value,
    /// Per-fixture tolerance override. When absent, the test's
    /// algorithm-class default is used.
    #[serde(default)]
    pub tolerance: Option<ToleranceOverride>,
    /// Reference to an entry in `_divergences.toml`. When set, this fixture
    /// documents a known and intentional divergence from sklearn — it is
    /// NOT a candidate for filing a bug report.
    #[serde(default)]
    pub divergence_id: Option<String>,
}

/// Per-fixture tolerance override.
#[derive(Debug, Deserialize, Clone, Copy)]
pub struct ToleranceOverride {
    #[serde(default)]
    pub rel: Option<f64>,
    #[serde(default)]
    pub abs: Option<f64>,
}

impl Fixture {
    /// Resolve effective (rel, abs) tolerance: per-fixture override falls
    /// back to the supplied algorithm-class default.
    #[must_use]
    pub fn tolerance(&self, default_rel: f64, default_abs: f64) -> (f64, f64) {
        let rel = self
            .tolerance
            .as_ref()
            .and_then(|t| t.rel)
            .unwrap_or(default_rel);
        let abs = self
            .tolerance
            .as_ref()
            .and_then(|t| t.abs)
            .unwrap_or(default_abs);
        (rel, abs)
    }

    /// True if this fixture is annotated as a documented divergence — in
    /// which case the conformance test should be informational only.
    #[must_use]
    pub fn is_documented_divergence(&self) -> bool {
        self.divergence_id.is_some()
    }
}

/// Load a fixture from a workspace-relative path under `fixtures/`.
///
/// Walks up from `CARGO_MANIFEST_DIR` to find the workspace root, then loads
/// `fixtures/<name>.json` (the trailing `.json` is added if missing).
#[must_use]
pub fn load_fixture(name: &str) -> Fixture {
    let path = fixture_path(name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {}: {e}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("failed to parse fixture {}: {e}", path.display()))
}

/// Resolve a fixture name to an absolute path. Works from any crate in the
/// workspace by walking up to find the `fixtures/` directory.
#[must_use]
pub fn fixture_path(name: &str) -> PathBuf {
    let file = if name.ends_with(".json") {
        name.to_string()
    } else {
        format!("{name}.json")
    };
    fixtures_dir().join(file)
}

/// Return the path to the workspace `fixtures/` directory.
///
/// Walks up from `CARGO_MANIFEST_DIR` looking for a `Cargo.toml` whose
/// content contains a `[workspace]` table (i.e. the workspace root), then
/// returns the `fixtures/` directory below it. This avoids picking up
/// per-crate `fixtures/` directories that some leaf crates ship
/// (`ferrolearn-kernel/fixtures/` holds crate-local samples that don't
/// match the workspace-level sklearn-reference schema).
#[must_use]
pub fn fixtures_dir() -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let manifest_path = Path::new(&manifest);
    let mut dir = manifest_path;
    loop {
        let cargo = dir.join("Cargo.toml");
        if cargo.is_file() {
            if let Ok(text) = std::fs::read_to_string(&cargo) {
                if text.contains("[workspace]") {
                    let candidate = dir.join("fixtures");
                    if candidate.is_dir() {
                        return candidate;
                    }
                }
            }
        }
        match dir.parent() {
            Some(p) => dir = p,
            None => panic!(
                "could not find workspace `fixtures/` directory walking up from {}",
                manifest_path.display()
            ),
        }
    }
}

// ---------------------------------------------------------------------------
// Divergence registry — parses `_divergences.toml`.
//
// A divergence entry documents a known case where ferrolearn intentionally
// differs from sklearn because sklearn is mathematically incorrect or
// because ferrolearn applies a documented improvement. Each entry must
// have a citation (paper / sklearn issue / numerical-analysis reference).
// ---------------------------------------------------------------------------

/// Single divergence entry.
#[derive(Debug, Deserialize, Clone)]
pub struct DivergenceEntry {
    pub id: String,
    pub estimator: String,
    pub description: String,
    pub citation: String,
    #[serde(default)]
    pub affected_fixtures: Vec<String>,
}

/// Parsed `_divergences.toml`.
#[derive(Debug, Deserialize, Default)]
pub struct DivergenceRegistry {
    #[serde(default, rename = "divergence")]
    pub entries: Vec<DivergenceEntry>,
}

impl DivergenceRegistry {
    /// Load from a TOML file. Returns an empty registry if the file doesn't
    /// exist (every crate starts out without any documented divergences).
    #[must_use]
    pub fn load(path: &Path) -> Self {
        if !path.exists() {
            return Self::default();
        }
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        toml::from_str(&text).unwrap_or_else(|e| panic!("invalid TOML in {}: {e}", path.display()))
    }

    #[must_use]
    pub fn get(&self, id: &str) -> Option<&DivergenceEntry> {
        self.entries.iter().find(|e| e.id == id)
    }
}

// ---------------------------------------------------------------------------
// Surface inventory + exclusions — `_surface_inventory.toml`,
// `_surface_exclusions.toml`. Used by per-crate coverage gates.
// ---------------------------------------------------------------------------

/// A public surface item that must have conformance coverage.
#[derive(Debug, Deserialize, Clone)]
pub struct SurfaceItem {
    /// Estimator name or function path (e.g., "LinearRegression",
    /// "metrics::accuracy_score").
    pub path: String,
    /// Logical phase / family tag (e.g., "linear", "tree-ensemble").
    #[serde(default)]
    pub phase: String,
    /// Fixture name without extension. Empty when the item is covered by
    /// a non-fixture test (rare — used for stateless utilities).
    #[serde(default)]
    pub fixture: String,
}

/// Surface inventory document.
#[derive(Debug, Deserialize, Default)]
pub struct SurfaceInventory {
    #[serde(default, rename = "item")]
    pub items: Vec<SurfaceItem>,
}

impl SurfaceInventory {
    #[must_use]
    pub fn load(path: &Path) -> Self {
        if !path.exists() {
            return Self::default();
        }
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        toml::from_str(&text).unwrap_or_else(|e| panic!("invalid TOML in {}: {e}", path.display()))
    }
}

/// A documented exclusion from the conformance requirement.
#[derive(Debug, Deserialize, Clone)]
pub struct ExclusionEntry {
    pub path: String,
    pub reason: String,
    #[serde(default)]
    pub covered_by: String,
}

/// Surface exclusions document.
#[derive(Debug, Deserialize, Default)]
pub struct SurfaceExclusions {
    #[serde(default, rename = "exclusion")]
    pub entries: Vec<ExclusionEntry>,
}

impl SurfaceExclusions {
    #[must_use]
    pub fn load(path: &Path) -> Self {
        if !path.exists() {
            return Self::default();
        }
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        toml::from_str(&text).unwrap_or_else(|e| panic!("invalid TOML in {}: {e}", path.display()))
    }

    #[must_use]
    pub fn contains(&self, path: &str) -> bool {
        self.entries.iter().any(|e| e.path == path)
    }
}

/// Verify that every inventory item is either:
///   1. listed in the exclusions file, OR
///   2. referenced (by literal text match) in at least one of the supplied
///      test source files.
///
/// Panics with a list of uncovered items. Used by per-crate
/// `conformance_surface_coverage.rs`.
pub fn assert_surface_covered(
    inventory: &SurfaceInventory,
    exclusions: &SurfaceExclusions,
    test_files: &[&Path],
) {
    // Concatenate all the test file text once.
    let mut haystack = String::new();
    for f in test_files {
        let text = std::fs::read_to_string(f)
            .unwrap_or_else(|e| panic!("could not read test file {}: {e}", f.display()));
        haystack.push_str(&text);
        haystack.push('\n');
    }
    let mut missing: Vec<String> = Vec::new();
    for item in &inventory.items {
        if exclusions.contains(&item.path) {
            continue;
        }
        // Strip namespace prefix before matching — we just need a leaf
        // name to appear textually.
        let leaf = item.path.rsplit("::").next().unwrap_or(&item.path);
        if haystack.contains(leaf) {
            continue;
        }
        missing.push(item.path.clone());
    }
    assert!(
        missing.is_empty(),
        "Surface coverage gap — the following public items have no conformance \
         reference and no exclusion entry:\n  - {}\n\n\
         To resolve: add a conformance test that mentions the symbol, or add an \
         entry to `tests/conformance/_surface_exclusions.toml`.",
        missing.join("\n  - ")
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn close_passes_within_tolerance() {
        assert_close(1.0, 1.0 + 1e-10, 1e-9, 1e-12, "tight");
        assert_close(0.0, 1e-13, 0.0, 1e-12, "near zero");
    }

    #[test]
    #[should_panic(expected = "diff=")]
    fn close_panics_outside_tolerance() {
        assert_close(1.0, 1.5, 1e-9, 1e-12, "too far");
    }

    #[test]
    fn close_handles_nan() {
        assert_close(f64::NAN, f64::NAN, 1e-9, 1e-12, "nan");
    }

    #[test]
    #[should_panic(expected = "NaN mismatch")]
    fn close_panics_nan_vs_finite() {
        assert_close(f64::NAN, 1.0, 1e-9, 1e-12, "mixed");
    }

    #[test]
    fn close_handles_signed_infinity() {
        assert_close(f64::INFINITY, f64::INFINITY, 1e-9, 1e-12, "+inf");
        assert_close(f64::NEG_INFINITY, f64::NEG_INFINITY, 1e-9, 1e-12, "-inf");
    }

    #[test]
    fn ari_identical_labels() {
        let a = vec![0i64, 0, 1, 1, 2, 2];
        let b = vec![0i64, 0, 1, 1, 2, 2];
        assert!((adjusted_rand_index(&a, &b) - 1.0).abs() < 1e-12);
    }

    #[test]
    fn ari_permuted_labels() {
        // Same clustering, different label assignment — ARI should still be 1.0.
        let a = vec![0i64, 0, 1, 1, 2, 2];
        let b = vec![2i64, 2, 0, 0, 1, 1];
        assert!((adjusted_rand_index(&a, &b) - 1.0).abs() < 1e-12);
    }

    #[test]
    fn ari_independent_labels() {
        let a = vec![0i64, 1, 0, 1, 0, 1];
        let b = vec![0i64, 0, 1, 1, 0, 1];
        // Should be small, between -0.5 and 0.5 typically.
        let ari = adjusted_rand_index(&a, &b);
        assert!(ari.abs() < 0.5, "expected ARI near 0, got {ari}");
    }

    #[test]
    fn json_to_array2_round_trip() {
        let v = serde_json::json!([[1.0, 2.0], [3.0, 4.0]]);
        let arr = json_to_array2(&v);
        assert_eq!(arr.shape(), &[2, 2]);
        assert_eq!(arr[[0, 0]], 1.0);
        assert_eq!(arr[[1, 1]], 4.0);
    }

    #[test]
    fn json_to_array1_handles_nan_strings() {
        let v = serde_json::json!([1.0, "NaN", "Infinity", -2.0]);
        let arr = json_to_array1(&v);
        assert_eq!(arr.len(), 4);
        assert_eq!(arr[0], 1.0);
        assert!(arr[1].is_nan());
        assert_eq!(arr[2], f64::INFINITY);
        assert_eq!(arr[3], -2.0);
    }

    #[test]
    fn fixture_default_tolerance() {
        let fx = Fixture {
            description: String::new(),
            sklearn_version: None,
            sklearn_pin: None,
            random_state: None,
            input: serde_json::Value::Null,
            params: serde_json::Value::Null,
            expected: serde_json::Value::Null,
            tolerance: None,
            divergence_id: None,
        };
        let (rel, abs) = fx.tolerance(1e-6, 1e-9);
        assert_eq!(rel, 1e-6);
        assert_eq!(abs, 1e-9);
    }

    #[test]
    fn fixture_tolerance_override() {
        let fx = Fixture {
            description: String::new(),
            sklearn_version: None,
            sklearn_pin: None,
            random_state: None,
            input: serde_json::Value::Null,
            params: serde_json::Value::Null,
            expected: serde_json::Value::Null,
            tolerance: Some(ToleranceOverride {
                rel: Some(1e-3),
                abs: Some(1e-5),
            }),
            divergence_id: None,
        };
        let (rel, abs) = fx.tolerance(1e-6, 1e-9);
        assert_eq!(rel, 1e-3);
        assert_eq!(abs, 1e-5);
    }
}
