//! Oracle fixture tests — compare Rust predictions against Python reference.
//!
//! Fixture JSON files were generated by the Python `kernel-regression` package
//! with known seeds, kernel, and bandwidth. We verify that the Rust
//! implementation reproduces the same results within tolerance.

use ndarray::{Array1, Array2, array};
use serde::Deserialize;

use ferrolearn_core::{Fit, Predict};
use ferrolearn_kernel::bandwidth::BandwidthStrategy;
use ferrolearn_kernel::kernels::GaussianKernel;
use ferrolearn_kernel::local_polynomial::LocalPolynomialRegression;
use ferrolearn_kernel::weights;

/// Schema for `nw_gaussian_sin.json` and `lpr_order1_sin.json`.
#[derive(Deserialize)]
struct SinFixture {
    #[serde(rename = "X")]
    x: Vec<Vec<f64>>,
    y: Vec<f64>,
    predictions: Vec<f64>,
    bandwidth: Vec<f64>,
}

/// Schema for `boundary_test.json`.
#[derive(Deserialize)]
struct BoundaryFixture {
    #[serde(rename = "X_train")]
    x_train: Vec<Vec<f64>>,
    y_train: Vec<f64>,
    #[serde(rename = "X_test")]
    x_test: Vec<Vec<f64>>,
    nw_predictions: Vec<f64>,
    lpr_predictions: Vec<f64>,
    bandwidth: f64,
}

fn vec2d_to_array2(v: &[Vec<f64>]) -> Array2<f64> {
    let n = v.len();
    let d = v[0].len();
    let flat: Vec<f64> = v.iter().flat_map(|row| row.iter().copied()).collect();
    Array2::from_shape_vec((n, d), flat).unwrap()
}

fn load_fixture<T: serde::de::DeserializeOwned>(name: &str) -> T {
    let path = format!("{}/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read fixture {path}: {e}"));
    serde_json::from_str(&data).unwrap_or_else(|e| panic!("Failed to parse fixture {path}: {e}"))
}

#[test]
fn nw_gaussian_sin_matches_python() {
    let fix: SinFixture = load_fixture("nw_gaussian_sin.json");
    let x = vec2d_to_array2(&fix.x);
    let y = Array1::from_vec(fix.y);
    let bw = Array1::from_vec(fix.bandwidth);

    let w = weights::compute_kernel_weights(&x, &x, &bw, &GaussianKernel);
    let pred = weights::nw_predict_from_weights(&w, &y);

    let python_pred = Array1::from_vec(fix.predictions);
    let max_err: f64 = pred
        .iter()
        .zip(python_pred.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f64, f64::max);

    assert!(
        max_err < 1e-8,
        "NW Gaussian sin: max error {max_err:.2e} exceeds 1e-8"
    );
}

#[test]
fn lpr_order1_sin_matches_python() {
    let fix: SinFixture = load_fixture("lpr_order1_sin.json");
    let x = vec2d_to_array2(&fix.x);
    let y = Array1::from_vec(fix.y.clone());

    let lpr = LocalPolynomialRegression::with_kernel(
        GaussianKernel,
        BandwidthStrategy::Fixed(fix.bandwidth[0]),
        1,
    );
    let fitted = lpr.fit(&x, &y).unwrap();
    let pred = fitted.predict(&x).unwrap();

    let python_pred = Array1::from_vec(fix.predictions);
    let max_err: f64 = pred
        .iter()
        .zip(python_pred.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f64, f64::max);

    // LPR solver differences may cause slightly larger deviation
    assert!(
        max_err < 1e-4,
        "LPR order-1 sin: max error {max_err:.2e} exceeds 1e-4"
    );
}

#[test]
fn boundary_nw_matches_python() {
    let fix: BoundaryFixture = load_fixture("boundary_test.json");
    let x_train = vec2d_to_array2(&fix.x_train);
    let y_train = Array1::from_vec(fix.y_train);
    let x_test = vec2d_to_array2(&fix.x_test);
    let bw = array![fix.bandwidth];

    let w = weights::compute_kernel_weights(&x_test, &x_train, &bw, &GaussianKernel);
    let pred = weights::nw_predict_from_weights(&w, &y_train);

    let python_pred = Array1::from_vec(fix.nw_predictions);
    let max_err: f64 = pred
        .iter()
        .zip(python_pred.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f64, f64::max);

    assert!(
        max_err < 1e-8,
        "Boundary NW: max error {max_err:.2e} exceeds 1e-8"
    );
}

#[test]
fn boundary_lpr_matches_python() {
    let fix: BoundaryFixture = load_fixture("boundary_test.json");
    let x_train = vec2d_to_array2(&fix.x_train);
    let y_train = Array1::from_vec(fix.y_train.clone());
    let x_test = vec2d_to_array2(&fix.x_test);

    let lpr = LocalPolynomialRegression::with_kernel(
        GaussianKernel,
        BandwidthStrategy::Fixed(fix.bandwidth),
        1,
    );
    let fitted = lpr.fit(&x_train, &y_train).unwrap();
    let pred = fitted.predict(&x_test).unwrap();

    let python_pred = Array1::from_vec(fix.lpr_predictions);
    let max_err: f64 = pred
        .iter()
        .zip(python_pred.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f64, f64::max);

    // LPR boundary predictions should be close
    assert!(
        max_err < 1e-4,
        "Boundary LPR: max error {max_err:.2e} exceeds 1e-4"
    );
}

#[test]
fn boundary_lpr_less_biased_than_nw() {
    // On y=x data, NW biases toward the mean at boundaries; LPR should not.
    let fix: BoundaryFixture = load_fixture("boundary_test.json");
    let x_train = vec2d_to_array2(&fix.x_train);
    let y_train = Array1::from_vec(fix.y_train.clone());
    let x_test = vec2d_to_array2(&fix.x_test);
    let bw = array![fix.bandwidth];

    // NW predictions
    let w = weights::compute_kernel_weights(&x_test, &x_train, &bw, &GaussianKernel);
    let nw_pred = weights::nw_predict_from_weights(&w, &y_train);

    // LPR predictions
    let lpr = LocalPolynomialRegression::with_kernel(
        GaussianKernel,
        BandwidthStrategy::Fixed(fix.bandwidth),
        1,
    );
    let fitted = lpr.fit(&x_train, &y_train).unwrap();
    let lpr_pred = fitted.predict(&x_test).unwrap();

    // True values at test points
    let y_true: Vec<f64> = fix.x_test.iter().map(|row| row[0]).collect();

    let nw_err: f64 = nw_pred
        .iter()
        .zip(y_true.iter())
        .map(|(p, t)| (p - t).abs())
        .sum::<f64>();
    let lpr_err: f64 = lpr_pred
        .iter()
        .zip(y_true.iter())
        .map(|(p, t)| (p - t).abs())
        .sum::<f64>();

    assert!(
        lpr_err < nw_err,
        "LPR total error ({lpr_err:.6}) should be less than NW ({nw_err:.6})"
    );
}
