//! Divergence: `BayesianRidge` final `scores_` entry diverges from sklearn.
//!
//! sklearn's `BayesianRidge.fit` appends a *post-loop* log-marginal-likelihood
//! entry to `scores_` (`sklearn/linear_model/_bayes.py:325-330`). That call
//! reuses the LOCAL `coef_` from the last in-loop iteration together with a
//! freshly recomputed `rmse_`:
//!
//!   `_bayes.py:322` — `self.coef_, rmse_ = self._update_coef_(... alpha_, lambda_)`
//!   `_bayes.py:327` — `s = self._log_marginal_likelihood(..., alpha_, lambda_, coef_, rmse_)`
//!
//! Note the score at line 327 passes `coef_` (the LOOP-LOCAL posterior mean,
//! computed with the *pre-final* alpha_/lambda_ — i.e. the iterate that
//! triggered the convergence break), NOT `self.coef_` (which line 322 just
//! recomputed with the FINAL alpha_/lambda_). The `rmse_`, however, IS the
//! freshly recomputed one. sklearn therefore stores a final `scores_` value
//! built from a *mismatched* (coef_, rmse_) pair — a pin of sklearn's exact
//! observable behavior.
//!
//! ferrolearn (`ferrolearn-linear/src/bayesian_ridge.rs:676-691`) instead
//! recomputes the final `coef` AND passes that same final `coef` (consistent
//! with the final alpha_/lambda_) to the post-loop `log_marginal_likelihood`.
//! ferrolearn's `scores_.last()` is thus the *self-consistent* value, which
//! differs from sklearn's stored `scores_[-1]` whenever the last in-loop coef
//! differs from the final recomputed coef (i.e. on any non-degenerate fit).
//!
//! Per-iteration `scores_[0..n_iter_]` match sklearn to machine precision
//! (≤1e-15 relative), so the LML *formula* is correct — only the post-loop
//! entry's coef argument diverges. The pre-existing
//! `divergence_bayesian_ridge_scores_30x5_final` masks this with a
//! `1e-5 * |val|` (~3e-4) tolerance; the real gap is ~7.7e-8 (default) and the
//! divergence is sign/value-stable, so this test pins it at 1e-9.
//!
//! Expected values are the LIVE sklearn 1.5.2 oracle `m.scores_[-1]` (R-CHAR-3),
//! generated by the script quoted in each test, NOT copied from ferrolearn.
//!
//! Tracking: #2162

use ferrolearn_core::traits::Fit;
use ferrolearn_linear::BayesianRidge;
use ndarray::{Array1, Array2};

/// The exact 30x5 regularization-sensitive design from
/// `divergence_bayesian_ridge_fit.rs::dataset()`.
fn dataset() -> (Array2<f64>, Array1<f64>) {
    (
        Array2::from_shape_vec((30, 5), X_FLAT.to_vec()).unwrap(),
        Array1::from_vec(Y_FLAT.to_vec()),
    )
}

/// Live sklearn 1.5.2 oracle on `dataset()`:
///   python3 -c "import numpy as np; from sklearn.linear_model import BayesianRidge; \
///     X=<dataset()>.reshape(30,5); y=<dataset()>; \
///     print(BayesianRidge(compute_score=True).fit(X,y).scores_[-1])"   # default
///   -> -31.363808685342036
/// and with non-default hyperpriors (alpha_1=1e-3, alpha_2=2e-3,
///    lambda_1=3e-3, lambda_2=4e-3): -> -31.375951060428644
#[test]
fn divergence_bayesian_ridge_scores_final_postloop_coef() {
    const SK_FINAL_DEFAULT: f64 = -31.363808685342036;
    const SK_FINAL_NONDEFAULT: f64 = -31.375951060428644;

    let (x, y) = dataset();

    // ---- default hyperpriors ----
    let f = BayesianRidge::<f64>::new()
        .with_compute_score(true)
        .fit(&x, &y)
        .unwrap();
    let got = *f.scores().last().unwrap();
    assert!(
        (got - SK_FINAL_DEFAULT).abs() < 1e-9 * SK_FINAL_DEFAULT.abs(),
        "default: final scores_ ferrolearn={got}, sklearn={SK_FINAL_DEFAULT} \
         (abs diff {})",
        (got - SK_FINAL_DEFAULT).abs()
    );

    // ---- non-default hyperpriors (hyperprior-term sensitive) ----
    let f2 = BayesianRidge::<f64>::new()
        .with_compute_score(true)
        .with_alpha_1(1e-3)
        .with_alpha_2(2e-3)
        .with_lambda_1(3e-3)
        .with_lambda_2(4e-3)
        .fit(&x, &y)
        .unwrap();
    let got2 = *f2.scores().last().unwrap();
    assert!(
        (got2 - SK_FINAL_NONDEFAULT).abs() < 1e-9 * SK_FINAL_NONDEFAULT.abs(),
        "non-default: final scores_ ferrolearn={got2}, sklearn={SK_FINAL_NONDEFAULT} \
         (abs diff {})",
        (got2 - SK_FINAL_NONDEFAULT).abs()
    );
}

#[rustfmt::skip]
const X_FLAT: [f64; 150] = [
    1.764052345967664, 0.4001572083672233, 0.9787379841057392, 0.24932698444308188,
    1.5808229508384346, -0.977277879876411, 0.9500884175255894, -0.1513572082976979,
    0.48508047533686777, -0.7082158197238333, 0.144043571160878, 1.454273506962975,
    0.7610377251469934, 1.034695125003802, 0.0551637318399462, 0.33367432737426683,
    1.4940790731576061, -0.20515826376580087, 0.7505826280811996, 0.21766304077093873,
    -2.5529898158340787, 0.6536185954403606, 0.8644361988595057, 0.6479411665577259,
    -2.307536086693214, -1.4543656745987648, 0.04575851730144607, -0.1871838500258336,
    -0.28380471728019274, -1.375276935775099, 0.1549474256969163, 0.37816251960217356,
    -0.8877857476301128, 0.08165334779604874, 0.2521162753378754, 0.15634896910398005,
    1.2302906807277207, 1.2023798487844113, 0.9946655604343716, 0.032720921357239724,
    -1.0485529650670926, -1.4200179371789752, -1.7062701906250126, -1.2839269490214429,
    -1.0584445338014936, -0.4380743016111864, -1.2527953600499262, 0.7774903558319101,
    -0.6936333689585937, -0.43804887592451114, -0.8954665611936756, 0.386902497859262,
    -0.510805137568873, 0.05095061634271991, -0.8557231501435386, 0.42833187053041766,
    0.06651722238316789, 0.3024718977397814, 0.1066239517763709, 0.5784518888590745,
    -0.672460447775951, -0.3595531615405413, -0.813146282044454, -0.2954990928779322,
    -0.5102723223057799, -0.4017809362082619, -1.6301983469660446, 0.4627822555257742,
    -1.5377773771210752, -0.3528477184489166, 0.7290905621775369, 0.12898291075741067,
    1.1394006845433007, 0.20784166071227927, 0.5336379540767664, -0.6848100909403132,
    -0.8707971491818818, -0.5788496647644155, -0.7309469855899551, -0.5318927842061272,
    -1.1651498407833565, 0.9008264869541871, 0.46566243973045984, 0.8750192998060832,
    -1.1486563914439771, 1.8958891760305832, 1.1787795711596507, -0.17992483581235091,
    1.1077244877204668, 1.5518231487497638, -0.40317694697317963, 1.2224450703824274,
    0.2082749780768603, 1.4106032461620799, -0.2440562730406315, 0.7065731681919482,
    0.010500020720820478, 1.7858704939058352, 0.2757056064639348, 0.6676101125652383,
    1.8831506970562544, -1.3477590611424464, -1.2704849984857336, -1.152043616502446,
    1.7869215097287108, 1.9436211856492926, -0.41361898075974735, -0.7474548114407578,
    -0.37877102012298314, 1.7811318323786656, 1.8675589604265699, 0.9060446582753853,
    -0.8612256850547025, 0.9447676457977309, 1.766486125574182, 0.8024563957963952,
    0.947251967773748, -0.1550100930908342, 0.888854320363518, 0.6571081968867409,
    0.37642553115562943, -1.0994007905841945, 0.298238174206056, -0.7514943272478373,
    0.23535869386162006, -0.14963454032767076, -0.43515355172163744, 1.8492637284793418,
    -0.6715140502394769, -0.06651163446674098, -0.7699160744453164, 0.5392491912918173,
    -0.6743326606573761, 0.4265341281536667, -0.7732654334181689, 0.6764332949464997,
    0.5765908166149409, -0.20829875557799488, 0.31366647145081505, 0.5398349876768298,
    -1.4912575927056055, 0.4393917012645369, 0.16667349537252904, 0.4074982808202772,
    -1.3876850837867793, 0.9444794869904138, -0.9128222254441586, 1.117016288095853,
    -0.7498878582839186, 0.8517794541938781,
];
#[rustfmt::skip]
const Y_FLAT: [f64; 30] = [
    7.3181665014724935, -5.735725096670511, -2.0005067216289083, -1.8938501514039752,
    -12.899733896381903, -6.722554308663109, 0.07818144396249455, -1.7528772043301009,
    -0.7636353462001417, 0.5131659255492051, -5.221761904761247, 1.8466481122638356,
    -2.2954814910284873, 1.7665230445206597, 1.9593642889106269, -1.079044153666201,
    -6.941833814441722, 5.7739336269972314, -4.319163425728022, 2.9811737671140577,
    10.313322023555456, 9.083139325354274, 6.168886015081853, 1.7065525703025137,
    3.103024999516751, 0.7122350816151478, -3.800902483801152, 0.6508782206180959,
    -7.220954440937009, 6.2752061106655,
];
