//! Divergence pins for `HuberRegressor::fit` against the live sklearn 1.5.2
//! oracle (`sklearn/linear_model/_huber.py`).
//!
//! sklearn jointly optimizes `[coef, intercept, scale]` with L-BFGS-B over
//! `_huber_loss_and_gradient` (`sklearn/linear_model/_huber.py:325`), where the
//! inlier/outlier split is `|y - Xw - c| > epsilon * sigma`
//! (`sklearn/linear_model/_huber.py:67`) and `sigma` is bounded strictly
//! positive (`sklearn/linear_model/_huber.py:323`). ferrolearn instead runs
//! IRLS reweighted ridge with **no scale parameter**, so its outlier band is a
//! raw `epsilon` (≈1.35) rather than `epsilon * scale` (≈0.11 on this data).
//!
//! Expected values are loaded from `tests/fixtures/huber_oracle.json`, which is
//! generated by calling sklearn 1.5.2 directly (NOT copied from ferrolearn).

use ferrolearn_core::introspection::HasCoefficients;
use ferrolearn_core::traits::Fit;
use ferrolearn_linear::HuberRegressor;
use ndarray::{Array1, Array2};

/// Oracle fixture: data + sklearn 1.5.2 expected fitted attributes.
struct Oracle {
    x: Array2<f64>,
    y_outlier: Array1<f64>,
    y_clean: Array1<f64>,
    sk_outlier_coef: Vec<f64>,
    sk_outlier_intercept: f64,
    sk_outlier_scale: f64,
    sk_clean_coef: Vec<f64>,
    sk_clean_intercept: f64,
    sk_eps15_epsilon: f64,
    sk_eps15_coef: Vec<f64>,
    sk_eps15_intercept: f64,
    sk_eps15_scale: f64,
    sk_eps15_outliers_count: usize,
    // sample_weight (REQ-11)
    sw_weights: Vec<f64>,
    sw_coef: Vec<f64>,
    sw_intercept: f64,
    sw_scale: f64,
    // warm_start (REQ-10)
    ws_cold_coef: Vec<f64>,
    ws_cold_intercept: f64,
    ws_cold_scale: f64,
    ws_warm_coef: Vec<f64>,
    ws_warm_intercept: f64,
    ws_warm_scale: f64,
}

fn load_oracle() -> Oracle {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/huber_oracle.json"
    ))
    .expect("read huber_oracle.json fixture");
    let v: serde_json::Value = serde_json::from_str(&raw).expect("parse huber_oracle.json");

    let to_mat = |rows: &serde_json::Value| -> Array2<f64> {
        let rows = rows.as_array().unwrap();
        let n = rows.len();
        let m = rows[0].as_array().unwrap().len();
        let mut flat = Vec::with_capacity(n * m);
        for r in rows {
            for c in r.as_array().unwrap() {
                flat.push(c.as_f64().unwrap());
            }
        }
        Array2::from_shape_vec((n, m), flat).unwrap()
    };
    let to_vec = |arr: &serde_json::Value| -> Vec<f64> {
        arr.as_array()
            .unwrap()
            .iter()
            .map(|e| e.as_f64().unwrap())
            .collect()
    };

    Oracle {
        x: to_mat(&v["X"]),
        y_outlier: Array1::from(to_vec(&v["y_outlier"])),
        y_clean: Array1::from(to_vec(&v["y_clean"])),
        sk_outlier_coef: to_vec(&v["sklearn_outlier"]["coef"]),
        sk_outlier_intercept: v["sklearn_outlier"]["intercept"].as_f64().unwrap(),
        sk_outlier_scale: v["sklearn_outlier"]["scale"].as_f64().unwrap(),
        sk_clean_coef: to_vec(&v["sklearn_clean"]["coef"]),
        sk_clean_intercept: v["sklearn_clean"]["intercept"].as_f64().unwrap(),
        sk_eps15_epsilon: v["sklearn_outlier_eps15"]["epsilon"].as_f64().unwrap(),
        sk_eps15_coef: to_vec(&v["sklearn_outlier_eps15"]["coef"]),
        sk_eps15_intercept: v["sklearn_outlier_eps15"]["intercept"].as_f64().unwrap(),
        sk_eps15_scale: v["sklearn_outlier_eps15"]["scale"].as_f64().unwrap(),
        sk_eps15_outliers_count: v["sklearn_outlier_eps15"]["outliers_count"]
            .as_u64()
            .unwrap() as usize,
        sw_weights: to_vec(&v["sample_weight"]["weights"]),
        sw_coef: to_vec(&v["sample_weight"]["coef"]),
        sw_intercept: v["sample_weight"]["intercept"].as_f64().unwrap(),
        sw_scale: v["sample_weight"]["scale"].as_f64().unwrap(),
        ws_cold_coef: to_vec(&v["warm_start"]["cold_coef"]),
        ws_cold_intercept: v["warm_start"]["cold_intercept"].as_f64().unwrap(),
        ws_cold_scale: v["warm_start"]["cold_scale"].as_f64().unwrap(),
        ws_warm_coef: to_vec(&v["warm_start"]["warm_coef"]),
        ws_warm_intercept: v["warm_start"]["warm_intercept"].as_f64().unwrap(),
        ws_warm_scale: v["warm_start"]["warm_scale"].as_f64().unwrap(),
    }
}

/// Divergence (PRIMARY, #495): `HuberRegressor::fit` diverges from
/// `sklearn/linear_model/_huber.py:325` on the outlier dataset.
///
/// Input: `X = RandomState(0).randn(50,3)`, `y = X@[1,2,-1] + 0.1*randn(50)`,
/// `y[:5] += 20`. Default `HuberRegressor` (epsilon=1.35, alpha=1e-4).
///
/// sklearn returns `coef_ ≈ [0.990, 1.980, -0.999]`, `intercept_ ≈ 0.0095`,
/// `scale_ ≈ 0.082`. ferrolearn's IRLS returns `coef ≈ [1.742, 2.357, -0.643]`,
/// `intercept ≈ 1.749` — coef[0] off by ~0.75, intercept off by ~1.74. This is
/// ALGORITHMIC (the IRLS band lacks `sigma`): raising `max_iter` cannot close
/// it. Root cause is the absent `scale_` (#496) — the outlier band is a fixed
/// `epsilon` instead of `epsilon * scale`.
///
/// Tracking: #495, #496 (scale_ jointly optimized), #497 (outliers_)
#[test]
fn divergence_huber_fit_outlier_dataset() {
    let o = load_oracle();

    let fitted = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_outlier)
        .expect("fit on outlier data");

    let coef = ferrolearn_core::introspection::HasCoefficients::coefficients(&fitted);
    let intercept = ferrolearn_core::introspection::HasCoefficients::intercept(&fitted);

    for (i, &sk) in o.sk_outlier_coef.iter().enumerate() {
        assert!(
            (coef[i] - sk).abs() < 1e-3,
            "coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6} (diff {:.4})",
            coef[i],
            (coef[i] - sk).abs()
        );
    }
    assert!(
        (intercept - o.sk_outlier_intercept).abs() < 1e-3,
        "intercept: sklearn={:.6}, ferrolearn={intercept:.6} (diff {:.4})",
        o.sk_outlier_intercept,
        (intercept - o.sk_outlier_intercept).abs()
    );

    // #496: scale_ is jointly optimized and matches sklearn's scale_.
    let scale = fitted.scale();
    assert!(
        (scale - o.sk_outlier_scale).abs() < 1e-3,
        "scale_: sklearn={:.6}, ferrolearn={scale:.6} (diff {:.4})",
        o.sk_outlier_scale,
        (scale - o.sk_outlier_scale).abs()
    );

    // #497: outliers_ flags the 5 injected outliers (y[:5] += 20).
    let outliers = fitted.outliers();
    assert_eq!(outliers.len(), o.y_outlier.len());
    for i in 0..5 {
        assert!(outliers[i], "injected outlier {i} must be flagged");
    }
}

/// Divergence (#495/#496): `HuberRegressor::fit` does not converge to sklearn's
/// fitted `coef_` even when `max_iter` is raised far beyond sklearn's count,
/// proving the gap is ALGORITHMIC (missing joint `scale`), not a convergence
/// tolerance gap. sklearn converges in `n_iter_ = 15`
/// (`sklearn/linear_model/_huber.py:342`); ferrolearn with `max_iter = 10000`
/// still does not match.
///
/// Tracking: #495
#[test]
fn divergence_huber_fit_not_convergence_max_iter() {
    let o = load_oracle();

    let fitted = HuberRegressor::<f64>::new()
        .with_max_iter(10_000)
        .with_tol(1e-12)
        .fit(&o.x, &o.y_outlier)
        .expect("fit on outlier data");

    let coef = ferrolearn_core::introspection::HasCoefficients::coefficients(&fitted);
    // coef[0] in particular is off by ~0.75 regardless of iteration budget.
    assert!(
        (coef[0] - o.sk_outlier_coef[0]).abs() < 1e-3,
        "coef[0] with max_iter=10000: sklearn={:.6}, ferrolearn={:.6} (diff {:.4}) \
         — unchanged from default max_iter, confirming algorithmic divergence",
        o.sk_outlier_coef[0],
        coef[0],
        (coef[0] - o.sk_outlier_coef[0]).abs()
    );
    // Pin the missing scale_ as the root cause (sklearn scale_ ≈ 0.082).
    assert!(
        o.sk_outlier_scale > 0.0 && o.sk_outlier_scale < 0.2,
        "fixture sanity: sklearn scale_ in (0,0.2)"
    );
}

/// Control (#495): on the CLEAN (no-outlier) dataset Huber ≈ OLS, so ferrolearn
/// is expected to match sklearn's `coef_`/`intercept_` within a loose tolerance.
/// This isolates the divergence to outlier handling (the scale band). Left
/// un-ignored: if it passes it confirms the regression locus; if it fails it is
/// itself a divergence to pin.
///
/// sklearn (clean): `coef_ ≈ [0.975, 1.983, -1.009]`, `intercept_ ≈ -0.006`.
#[test]
fn control_huber_fit_clean_dataset_matches_sklearn() {
    let o = load_oracle();

    let fitted = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_clean)
        .expect("fit on clean data");

    let coef = ferrolearn_core::introspection::HasCoefficients::coefficients(&fitted);
    let intercept = ferrolearn_core::introspection::HasCoefficients::intercept(&fitted);

    // Loose tolerance: Huber with tiny noise should land near OLS / sklearn.
    for (i, &sk) in o.sk_clean_coef.iter().enumerate() {
        assert!(
            (coef[i] - sk).abs() < 5e-2,
            "clean coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6} (diff {:.4})",
            coef[i],
            (coef[i] - sk).abs()
        );
    }
    assert!(
        (intercept - o.sk_clean_intercept).abs() < 5e-2,
        "clean intercept: sklearn={:.6}, ferrolearn={intercept:.6} (diff {:.4})",
        o.sk_clean_intercept,
        (intercept - o.sk_clean_intercept).abs()
    );
}

/// Parity (#495/#496/#497) with a DIFFERENT `epsilon`. Same outlier dataset,
/// `HuberRegressor(epsilon=1.5)`. A second oracle point guards against an
/// epsilon-specific coincidence: the joint `[coef, intercept, scale]` L-BFGS
/// must track sklearn as the inlier/outlier band `epsilon * scale` widens.
///
/// sklearn 1.5.2 (`epsilon=1.5`): `coef_ ≈ [0.9918, 1.9848, -0.9959]`,
/// `intercept_ ≈ 0.0106`, `scale_ ≈ 0.0997`, `outliers_.sum() == 11`.
#[test]
fn parity_huber_fit_outlier_dataset_epsilon_1_5() {
    let o = load_oracle();

    let fitted = HuberRegressor::<f64>::new()
        .with_epsilon(o.sk_eps15_epsilon)
        .fit(&o.x, &o.y_outlier)
        .expect("fit on outlier data (epsilon=1.5)");

    let coef = ferrolearn_core::introspection::HasCoefficients::coefficients(&fitted);
    let intercept = ferrolearn_core::introspection::HasCoefficients::intercept(&fitted);

    for (i, &sk) in o.sk_eps15_coef.iter().enumerate() {
        assert!(
            (coef[i] - sk).abs() < 1e-3,
            "eps=1.5 coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6} (diff {:.4})",
            coef[i],
            (coef[i] - sk).abs()
        );
    }
    assert!(
        (intercept - o.sk_eps15_intercept).abs() < 1e-3,
        "eps=1.5 intercept: sklearn={:.6}, ferrolearn={intercept:.6} (diff {:.4})",
        o.sk_eps15_intercept,
        (intercept - o.sk_eps15_intercept).abs()
    );
    let scale = fitted.scale();
    assert!(
        (scale - o.sk_eps15_scale).abs() < 1e-3,
        "eps=1.5 scale_: sklearn={:.6}, ferrolearn={scale:.6} (diff {:.4})",
        o.sk_eps15_scale,
        (scale - o.sk_eps15_scale).abs()
    );

    // #497: outliers_ count matches sklearn's mask cardinality.
    let n_out = fitted.outliers().iter().filter(|&&b| b).count();
    assert_eq!(
        n_out, o.sk_eps15_outliers_count,
        "eps=1.5 outliers_ count: sklearn={}, ferrolearn={n_out}",
        o.sk_eps15_outliers_count
    );
}

/// REQ-11 (#501): `sample_weight` parity. `HuberRegressor.fit_with_sample_weight`
/// must reproduce sklearn's weighted `coef_`/`intercept_`/`scale_`.
///
/// sklearn threads `sample_weight` through `_huber_loss_and_gradient`
/// (`sklearn/linear_model/_huber.py:18`, `:306`): each per-sample loss/gradient
/// term is multiplied by `w[i]` and `n_samples = np.sum(sample_weight)`
/// (`:59`). Weights are a seeded `|RandomState(42).randn| + 0.5` draw; the
/// expected attributes come from the live sklearn 1.5.2 oracle (R-CHAR-3).
#[test]
fn parity_huber_sample_weight_matches_sklearn() {
    let o = load_oracle();
    let w = Array1::from(o.sw_weights.clone());

    let fitted = HuberRegressor::<f64>::new()
        .fit_with_sample_weight(&o.x, &o.y_outlier, Some(&w))
        .expect("weighted fit");

    let coef = HasCoefficients::coefficients(&fitted);
    let intercept = HasCoefficients::intercept(&fitted);
    for (i, &sk) in o.sw_coef.iter().enumerate() {
        assert!(
            (coef[i] - sk).abs() < 1e-3,
            "sample_weight coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6} (diff {:.4})",
            coef[i],
            (coef[i] - sk).abs()
        );
    }
    assert!(
        (intercept - o.sw_intercept).abs() < 1e-3,
        "sample_weight intercept: sklearn={:.6}, ferrolearn={intercept:.6}",
        o.sw_intercept
    );
    assert!(
        (fitted.scale() - o.sw_scale).abs() < 1e-3,
        "sample_weight scale_: sklearn={:.6}, ferrolearn={:.6}",
        o.sw_scale,
        fitted.scale()
    );
}

/// REQ-11 (#501): `fit_with_sample_weight(x, y, None)` is byte-identical to
/// `Fit::fit(x, y)` (the unit-weight delegation). Guards that adding the weight
/// path did not perturb the default fit (sklearn `_check_sample_weight(None, X)`
/// returns `np.ones`, `_huber.py:306`).
#[test]
fn sample_weight_none_equals_fit() {
    let o = load_oracle();
    let a = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let b = HuberRegressor::<f64>::new()
        .fit_with_sample_weight(&o.x, &o.y_outlier, None)
        .unwrap();
    let (ca, cb) = (
        HasCoefficients::coefficients(&a),
        HasCoefficients::coefficients(&b),
    );
    for i in 0..ca.len() {
        assert_eq!(
            ca[i].to_bits(),
            cb[i].to_bits(),
            "coef[{i}] not byte-identical"
        );
    }
    assert_eq!(
        HasCoefficients::intercept(&a).to_bits(),
        HasCoefficients::intercept(&b).to_bits()
    );
    assert_eq!(a.scale().to_bits(), b.scale().to_bits());
}

/// REQ-11 (#501): uniform `sample_weight = 2.0` everywhere leaves the fitted
/// attributes essentially unchanged vs unit weights — a global scale of the
/// loss does not move the argmin (`n_samples` scales with it). Cross-checked
/// against sklearn, which exhibits the same invariance.
#[test]
fn sample_weight_uniform_invariant() {
    let o = load_oracle();
    let unit = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let w = Array1::from_elem(o.y_outlier.len(), 2.0_f64);
    let scaled = HuberRegressor::<f64>::new()
        .fit_with_sample_weight(&o.x, &o.y_outlier, Some(&w))
        .unwrap();
    let (cu, cs) = (
        HasCoefficients::coefficients(&unit),
        HasCoefficients::coefficients(&scaled),
    );
    for i in 0..cu.len() {
        assert!(
            (cu[i] - cs[i]).abs() < 1e-6,
            "uniform-weight coef[{i}] should match unit-weight: {} vs {}",
            cu[i],
            cs[i]
        );
    }
}

/// REQ-11 (#2159): a negative `sample_weight` is ACCEPTED and the fit matches
/// sklearn 1.5.2. sklearn's `HuberRegressor.fit` runs `sample_weight` through
/// `_check_sample_weight` (`sklearn/linear_model/_huber.py:306`), which imposes
/// NO non-negativity constraint — the negative weight flows into
/// `_huber_loss_and_gradient` and the fit converges. (The earlier
/// `sample_weight_negative_errors` asserted the OPPOSITE, masking this
/// divergence; R-CHAR-3 — the expected values below are from the live oracle.)
///
/// Oracle (R-CHAR-3), regenerated live on the fixture's `(X, y_outlier)`:
///   import json, numpy as np
///   from sklearn.linear_model import HuberRegressor
///   v = json.load(open('tests/fixtures/huber_oracle.json'))
///   X = np.array(v['X']); y = np.array(v['y_outlier'])
///   w = np.ones(len(y)); w[0] = -1.0
///   m = HuberRegressor().fit(X, y, sample_weight=w)
///   # coef_ ≈ [0.97333056, 1.97866157, -1.00309153]
///   # intercept_ ≈ 0.00275993, scale_ ≈ 0.06978982
#[test]
fn huber_negative_sample_weight_matches_sklearn() {
    let o = load_oracle();
    let mut w = Array1::from_elem(o.y_outlier.len(), 1.0_f64);
    w[0] = -1.0;
    let fitted = HuberRegressor::<f64>::new()
        .fit_with_sample_weight(&o.x, &o.y_outlier, Some(&w))
        .expect("sklearn 1.5.2 accepts negative sample_weight and returns a fitted model");

    let sk_coef = [0.9733305573123788, 1.9786615688203772, -1.0030915310948816];
    let sk_intercept = 0.0027599346547667125;
    let sk_scale = 0.06978982299856919;

    let coef = HasCoefficients::coefficients(&fitted);
    for (i, &sk) in sk_coef.iter().enumerate() {
        assert!(
            (coef[i] - sk).abs() < 1e-3,
            "neg-weight coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6}",
            coef[i]
        );
    }
    assert!(
        (HasCoefficients::intercept(&fitted) - sk_intercept).abs() < 1e-3,
        "neg-weight intercept: sklearn={sk_intercept:.6}, ferrolearn={:.6}",
        HasCoefficients::intercept(&fitted)
    );
    assert!(
        (fitted.scale() - sk_scale).abs() < 1e-3,
        "neg-weight scale_: sklearn={sk_scale:.6}, ferrolearn={:.6}",
        fitted.scale()
    );
}

/// REQ-10 (#500): `warm_start` reuses the prior `(coef, intercept, scale)` as
/// the optimizer seed and converges to the SAME optimum in FEWER iterations
/// (the Huber objective is convex). Mirrors sklearn `HuberRegressor(warm_start=
/// True)` (`sklearn/linear_model/_huber.py:265`, `:308-309`): a warm refit from
/// the converged solution drops `n_iter_` 15 -> 1 while the fitted attributes
/// are unchanged. The warm fit's `coef_`/`scale_` must still match the live
/// sklearn oracle (R-CHAR-3).
#[test]
fn parity_huber_warm_start_same_optimum() {
    let o = load_oracle();

    // Cold fit (R-DEV-4: supply the prior solution explicitly on the warm refit).
    let cold = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let cold_coef = HasCoefficients::coefficients(&cold).to_owned();
    let cold_int = HasCoefficients::intercept(&cold);
    let cold_scale = cold.scale();

    // Cold attributes already match sklearn's cold fit.
    for (i, &sk) in o.ws_cold_coef.iter().enumerate() {
        assert!(
            (cold_coef[i] - sk).abs() < 1e-3,
            "cold coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6}",
            cold_coef[i]
        );
    }
    assert!((cold_int - o.ws_cold_intercept).abs() < 1e-3);
    assert!((cold_scale - o.ws_cold_scale).abs() < 1e-3);

    // Warm refit from the converged solution.
    let warm = HuberRegressor::<f64>::new()
        .with_warm_start(true)
        .with_warm_start_state(cold_coef.clone(), cold_int, cold_scale)
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let warm_coef = HasCoefficients::coefficients(&warm);

    // Same optimum (sklearn warm == cold optimum), matching the oracle.
    for (i, &sk) in o.ws_warm_coef.iter().enumerate() {
        assert!(
            (warm_coef[i] - sk).abs() < 1e-3,
            "warm coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6}",
            warm_coef[i]
        );
        // And unchanged from the cold fit (convex unique minimum).
        assert!(
            (warm_coef[i] - cold_coef[i]).abs() < 1e-3,
            "warm coef[{i}] must equal cold coef",
        );
    }
    assert!((HasCoefficients::intercept(&warm) - o.ws_warm_intercept).abs() < 1e-3);
    assert!((warm.scale() - o.ws_warm_scale).abs() < 1e-3);
}

/// REQ-10: `warm_start` defaults are off and a default-config fit is unchanged.
#[test]
fn warm_start_default_off() {
    assert!(!HuberRegressor::<f64>::new().warm_start, "default off");
    assert!(HuberRegressor::<f64>::new().warm_start_state.is_none());
    // warm_start=true with NO state falls back to the cold path (byte-identical).
    let o = load_oracle();
    let a = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let b = HuberRegressor::<f64>::new()
        .with_warm_start(true)
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let (ca, cb) = (
        HasCoefficients::coefficients(&a),
        HasCoefficients::coefficients(&b),
    );
    for i in 0..ca.len() {
        assert_eq!(ca[i].to_bits(), cb[i].to_bits());
    }
}

/// REQ-10: a warm-start coef of the wrong length is rejected.
#[test]
fn warm_start_wrong_len_errors() {
    let o = load_oracle();
    let bad = Array1::from_elem(o.x.ncols() + 1, 0.0_f64);
    let r = HuberRegressor::<f64>::new()
        .with_warm_start(true)
        .with_warm_start_state(bad, 0.0, 1.0)
        .fit(&o.x, &o.y_outlier);
    assert!(r.is_err(), "wrong-length warm coef must error");
}

/// REQ-9 (#499): `FittedHuberRegressor::n_iter()` reports the REAL number of
/// ferrolearn L-BFGS iterations (sklearn `self.n_iter_ = opt_res.nit`,
/// `sklearn/linear_model/_huber.py:342`).
///
/// R-DEV-7 / R-CHAR-3: ferrolearn's in-repo L-BFGS is NOT scipy's bounded
/// L-BFGS-B, so the raw count is not asserted equal to sklearn's `n_iter_`.
/// The oracle-comparable contract asserted is the one sklearn ALSO satisfies:
/// `n_iter_` is a positive integer `<= max_iter` and is deterministic for a
/// fixed fit. (The warm-start < cold-start inequality is pinned separately in
/// `huber_warm_start_fewer_iters_than_cold`, mirroring sklearn cold `n_iter_=15`
/// vs warm `n_iter_=1`.)
#[test]
fn huber_n_iter_positive_bounded_and_deterministic() {
    let o = load_oracle();

    let max_iter = 200;
    let fit1 = HuberRegressor::<f64>::new()
        .with_max_iter(max_iter)
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let n1 = fit1.n_iter();

    // Positive and bounded by max_iter (sklearn caps n_iter_ at max_iter,
    // _huber.py:206-207).
    assert!(n1 >= 1, "n_iter must be a positive integer, got {n1}");
    assert!(
        n1 <= max_iter,
        "n_iter ({n1}) must be <= max_iter ({max_iter})"
    );

    // Deterministic: the same fit yields the same count.
    let fit2 = HuberRegressor::<f64>::new()
        .with_max_iter(max_iter)
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    assert_eq!(
        n1,
        fit2.n_iter(),
        "n_iter must be deterministic for a fixed fit"
    );
}

/// REQ-9 (#499): a warm-start refit converges in FEWER L-BFGS iterations than
/// the cold fit — the meaningful, oracle-comparable `n_iter_` property sklearn
/// also exhibits (live sklearn 1.5.2: cold `n_iter_=15`, warm `n_iter_=1`,
/// `sklearn/linear_model/_huber.py:308-309`/`:342`). Because the Huber objective
/// is convex with a unique minimum, seeding from the converged solution lands
/// the optimizer at (or adjacent to) the optimum, so it terminates sooner.
#[test]
fn huber_warm_start_fewer_iters_than_cold() {
    let o = load_oracle();

    // Cold fit.
    let cold = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let cold_iters = cold.n_iter();
    let cold_coef = HasCoefficients::coefficients(&cold).to_owned();
    let cold_int = HasCoefficients::intercept(&cold);
    let cold_scale = cold.scale();

    // Warm refit seeded from the converged cold solution.
    let warm = HuberRegressor::<f64>::new()
        .with_warm_start(true)
        .with_warm_start_state(cold_coef, cold_int, cold_scale)
        .fit(&o.x, &o.y_outlier)
        .unwrap();
    let warm_iters = warm.n_iter();

    assert!(
        warm_iters < cold_iters,
        "warm-start n_iter ({warm_iters}) must be < cold-start n_iter ({cold_iters}) \
         (sklearn: cold=15, warm=1)"
    );
    assert!(
        warm_iters >= 1,
        "warm n_iter must still be a positive integer"
    );
}
