//! Divergence pins for `QuantileRegressor::fit` against the live scikit-learn
//! 1.5.2 oracle (`sklearn/linear_model/_quantile.py`).
//!
//! sklearn builds the exact quantile-regression LINEAR PROGRAM and solves it
//! with `scipy.optimize.linprog` (HiGHS): decision vector
//! `x = (s0, s, t0, t, u, v) >= 0` with `intercept = s0 - t0`,
//! `coef = s - t`, residual `y - X@coef - intercept = u - v`, cost
//! `c = (0, alpha*1_p, 0, alpha*1_p, quantile*1_n, (1-quantile)*1_n)`,
//! `A_eq = (1_n, X, -1_n, -X, diag(1_n), -diag(1_n))`, `b_eq = y`
//! (`sklearn/linear_model/_quantile.py:218-269`). The intercept is therefore a
//! FREE LP VARIABLE and the fit depends on `quantile`:
//!   "Note that centering y and X with _preprocess_data does not work for
//!    quantile regression." (`sklearn/linear_model/_quantile.py:177`).
//!
//! ferrolearn now solves this exact LP with a self-contained two-phase primal
//! simplex (Bland's rule) in `fn fit` of `quantile_regressor.rs` (the intercept
//! is a free LP variable, not centering-recovered), reaching sklearn's HiGHS
//! vertex. Previously it fit via IRLS on a smoothed pinball loss and recovered
//! the intercept by centering, which made the fit quantile-INVARIANT and unable
//! to reach the LP's sparse vertex under regularization — the divergence these
//! tests pinned (now closed).
//!
//! Expected values are computed by the LIVE sklearn 1.5.2 oracle (R-CHAR-3),
//! NOT copied from the ferrolearn side. To regenerate:
//! ```text
//! python3 -c "
//! from sklearn.linear_model import QuantileRegressor
//! import numpy as np
//! rng=np.random.RandomState(0); X=rng.randn(30,3)
//! y=X@np.array([1.,2.,-1.])+0.5*rng.randn(30)
//! for q in (0.5,0.8):
//!   for a in (0.0,1.0):
//!     m=QuantileRegressor(quantile=q,alpha=a).fit(X,y)
//!     print(q,a,m.coef_.tolist(),m.intercept_)"
//! ```
//!
//! Tracking: #340 (IRLS vs HiGHS LP), #506 (centering intercept invalid for
//! quantile regression), #332 (alpha L1 sparse vertex).

use ferrolearn_core::introspection::HasCoefficients;
use ferrolearn_core::traits::Fit;
use ferrolearn_linear::QuantileRegressor;
use ndarray::{Array1, Array2};

/// Doc-author oracle dataset: `rng=RandomState(0); X=randn(30,3);
/// y=X@[1,2,-1]+0.5*randn(30)`. This is INPUT, not an expected value — the X
/// and y arrays are generated by numpy and only the sklearn fit outputs below
/// are the assertion targets.
fn oracle_dataset() -> (Array2<f64>, Array1<f64>) {
    let x_flat = vec![
        1.764052345967664,
        0.4001572083672233,
        0.9787379841057392,
        2.240893199201458,
        1.8675579901499675,
        -0.977277879876411,
        0.9500884175255894,
        -0.1513572082976979,
        -0.10321885179355784,
        0.41059850193837233,
        0.144043571160878,
        1.454273506962975,
        0.7610377251469934,
        0.12167501649282841,
        0.44386323274542566,
        0.33367432737426683,
        1.4940790731576061,
        -0.20515826376580087,
        0.31306770165090136,
        -0.8540957393017248,
        -2.5529898158340787,
        0.6536185954403606,
        0.8644361988595057,
        -0.7421650204064419,
        2.2697546239876076,
        -1.4543656745987648,
        0.04575851730144607,
        -0.1871838500258336,
        1.5327792143584575,
        1.469358769900285,
        0.1549474256969163,
        0.37816251960217356,
        -0.8877857476301128,
        -1.980796468223927,
        -0.3479121493261526,
        0.15634896910398005,
        1.2302906807277207,
        1.2023798487844113,
        -0.3873268174079523,
        -0.30230275057533557,
        -1.0485529650670926,
        -1.4200179371789752,
        -1.7062701906250126,
        1.9507753952317897,
        -0.5096521817516535,
        -0.4380743016111864,
        -1.2527953600499262,
        0.7774903558319101,
        -1.6138978475579515,
        -0.2127402802139687,
        -0.8954665611936756,
        0.386902497859262,
        -0.510805137568873,
        -1.180632184122412,
        -0.028182228338654868,
        0.42833187053041766,
        0.06651722238316789,
        0.3024718977397814,
        -0.6343220936809636,
        -0.3627411659871381,
        -0.672460447775951,
        -0.3595531615405413,
        -0.813146282044454,
        -1.7262826023316769,
        0.17742614225375283,
        -0.4017809362082619,
        -1.6301983469660446,
        0.4627822555257742,
        -0.9072983643832422,
        0.05194539579613895,
        0.7290905621775369,
        0.12898291075741067,
        1.1394006845433007,
        -1.2348258203536526,
        0.402341641177549,
        -0.6848100909403132,
        -0.8707971491818818,
        -0.5788496647644155,
        -0.31155253212737266,
        0.05616534222974544,
        -1.1651498407833565,
        0.9008264869541871,
        0.46566243973045984,
        -1.5362436862772237,
        1.4882521937955997,
        1.8958891760305832,
        1.1787795711596507,
        -0.17992483581235091,
        -1.0707526215105425,
        1.0544517269311366,
    ];
    let y = Array1::from(vec![
        1.3840403051097814,
        7.564509594569017,
        0.8547303417621815,
        -0.26726834446099035,
        0.7387077239744255,
        3.880277321551254,
        1.1631160492419408,
        4.017591260518731,
        -0.6212791961595581,
        1.6100104905131476,
        2.740633561059503,
        -3.5068492665514355,
        3.387134696461628,
        -0.4946923894515402,
        2.1183710790331407,
        -2.7493447847183026,
        -1.3507213371720868,
        0.1721970011235492,
        1.7234353035792047,
        0.13682627208220444,
        0.35535899140070537,
        -0.5166270524782166,
        -0.22794831405860533,
        2.3361760859433187,
        -1.8665942828172437,
        -1.4463265266414638,
        1.4395539770023487,
        3.2908900061469133,
        4.408290659870156,
        -2.9147784699813095,
    ]);
    let x = Array2::from_shape_vec((30, 3), x_flat).unwrap();
    (x, y)
}

// ---------------------------------------------------------------------------
// sklearn 1.5.2 HiGHS LP oracle constants (live oracle, NOT copied from ferro).
// ---------------------------------------------------------------------------

/// `QuantileRegressor(quantile=0.5, alpha=0.0).fit(X,y).intercept_`.
const SK_Q05_A0_INTERCEPT: f64 = 0.3242701963545993;
/// `QuantileRegressor(quantile=0.8, alpha=0.0).fit(X,y).intercept_`.
const SK_Q08_A0_INTERCEPT: f64 = 0.8814801705256051;
/// `QuantileRegressor(quantile=0.8, alpha=0.0).fit(X,y).coef_`.
const SK_Q08_A0_COEF: [f64; 3] = [0.8105308493753483, 2.1063600422551434, -0.9546586985136533];
/// Difference `intercept_(q=0.8) - intercept_(q=0.5)` at `alpha=0.0`.
const SK_INTERCEPT_DIFF_Q08_Q05: f64 = 0.5572099741710058;
/// `QuantileRegressor(quantile=0.2, alpha=0.0).fit(X,y).coef_` (extra parity case).
const SK_Q02_A0_COEF: [f64; 3] = [1.1124010932987514, 1.927469048094979, -1.0789864337813768];
/// `QuantileRegressor(quantile=0.2, alpha=0.0).fit(X,y).intercept_`.
const SK_Q02_A0_INTERCEPT: f64 = -0.29353907960416564;
/// `QuantileRegressor(quantile=0.8, alpha=1.0).fit(X,y).coef_` — exact sparse 0.
const SK_Q08_A1_COEF: [f64; 3] = [0.0, 0.0, 0.0];
/// `QuantileRegressor(quantile=0.5, alpha=1.0).fit(X,y).coef_` — exact sparse 0.
const SK_Q05_A1_COEF: [f64; 3] = [0.0, 0.0, 0.0];
/// `QuantileRegressor(quantile=0.5, alpha=1.0).fit(X,y).intercept_`.
const SK_Q05_A1_INTERCEPT: f64 = 0.7387077239744255;
/// `QuantileRegressor(quantile=0.8, alpha=1.0).fit(X,y).intercept_`.
const SK_Q08_A1_INTERCEPT: f64 = 2.740633561059503;

// ---------------------------------------------------------------------------
// PRIMARY pin (#340/#506): quantile-invariance / intercept divergence.
// ---------------------------------------------------------------------------

/// Divergence: ferrolearn's `QuantileRegressor::fit` diverges from
/// `sklearn/linear_model/_quantile.py:298-304` for `quantile=0.8, alpha=0.0`
/// on the doc-author dataset. sklearn's HiGHS LP returns `intercept_ ≈ 0.8815`
/// (the intercept is a free LP variable, `params[0] = s0 - t0`); ferrolearn's
/// centering-recovered intercept (`intercept = y_mean - x_mean·w`, `fn fit`)
/// returns ≈ 0.2988 — the SAME value as its `quantile=0.5` fit, because the
/// IRLS fit is quantile-invariant.
/// Tracking: #340, #506.
#[test]
fn divergence_quantile_08_intercept_diverges_from_lp() {
    let (x, y) = oracle_dataset();
    let fitted = QuantileRegressor::<f64>::new()
        .with_quantile(0.8)
        .with_alpha(0.0)
        .with_max_iter(2000)
        .fit(&x, &y)
        .unwrap();
    let intercept = fitted.intercept();
    assert!(
        (intercept - SK_Q08_A0_INTERCEPT).abs() < 1e-6,
        "q=0.8 alpha=0.0 intercept: sklearn {SK_Q08_A0_INTERCEPT}, ferrolearn {intercept}"
    );
}

/// Divergence: the fit is quantile-INVARIANT. sklearn's intercept changes by
/// ≈ 0.557 between `quantile=0.5` and `quantile=0.8`
/// (`sklearn/linear_model/_quantile.py:298-304`, the LP cost
/// `quantile*1_n / (1-quantile)*1_n` at `:241-242` shifts the optimum).
/// ferrolearn's centering intercept (`fn fit`) is identical across quantiles,
/// so the observed difference is ≈ 0 rather than ≈ 0.557.
/// Tracking: #506.
#[test]
fn divergence_quantile_intercept_must_change_with_quantile() {
    let (x, y) = oracle_dataset();
    let f05 = QuantileRegressor::<f64>::new()
        .with_quantile(0.5)
        .with_alpha(0.0)
        .with_max_iter(2000)
        .fit(&x, &y)
        .unwrap();
    let f08 = QuantileRegressor::<f64>::new()
        .with_quantile(0.8)
        .with_alpha(0.0)
        .with_max_iter(2000)
        .fit(&x, &y)
        .unwrap();
    let observed_diff = f08.intercept() - f05.intercept();
    assert!(
        (observed_diff - SK_INTERCEPT_DIFF_Q08_Q05).abs() < 1e-6,
        "intercept(q=0.8) - intercept(q=0.5): sklearn {SK_INTERCEPT_DIFF_Q08_Q05}, \
         ferrolearn {observed_diff} (≈0 — quantile-invariant fit)"
    );
}

/// Divergence: ferrolearn's `coef_` at `quantile=0.8, alpha=0.0` does not match
/// sklearn's LP vertex (`sklearn/linear_model/_quantile.py:303`); ferrolearn
/// returns its quantile=0.5 coefficients regardless of the quantile.
/// Tracking: #340.
#[test]
fn divergence_quantile_08_coef_diverges_from_lp() {
    let (x, y) = oracle_dataset();
    let fitted = QuantileRegressor::<f64>::new()
        .with_quantile(0.8)
        .with_alpha(0.0)
        .with_max_iter(2000)
        .fit(&x, &y)
        .unwrap();
    let coef = fitted.coefficients();
    for (j, &sk) in SK_Q08_A0_COEF.iter().enumerate() {
        assert!(
            (coef[j] - sk).abs() < 1e-6,
            "q=0.8 alpha=0.0 coef[{j}]: sklearn {sk}, ferrolearn {}",
            coef[j]
        );
    }
}

// ---------------------------------------------------------------------------
// alpha L1 sparse-vertex pin (#332).
// ---------------------------------------------------------------------------

/// Divergence: under `alpha=1.0` sklearn drives all coefficients to EXACTLY
/// zero — the LP sparse vertex (`sklearn/linear_model/_quantile.py:238-248`,
/// L1 cost `alpha*1_p`); the intercept stays a free variable
/// (`intercept_ ≈ 0.7387` at `quantile=0.5`). ferrolearn's IRLS-linearized
/// ridge penalty (`scaled_alpha / max(|w_j|, eps)` in `weighted_l1_solve`)
/// only reaches NEAR-zero coefficients with an identical ≈ 0.912 centering
/// intercept, so it cannot reach the LP vertex.
/// Tracking: #332, #340.
#[test]
fn divergence_alpha1_sparse_vertex() {
    let (x, y) = oracle_dataset();
    let fitted = QuantileRegressor::<f64>::new()
        .with_quantile(0.5)
        .with_alpha(1.0)
        .with_max_iter(2000)
        .fit(&x, &y)
        .unwrap();
    let coef = fitted.coefficients();
    for (j, &sk) in SK_Q05_A1_COEF.iter().enumerate() {
        assert!(
            (coef[j] - sk).abs() < 1e-8,
            "q=0.5 alpha=1.0 coef[{j}] must be EXACTLY zero (LP vertex): \
             sklearn {sk}, ferrolearn {}",
            coef[j]
        );
    }
    let intercept = fitted.intercept();
    assert!(
        (intercept - SK_Q05_A1_INTERCEPT).abs() < 1e-6,
        "q=0.5 alpha=1.0 intercept: sklearn {SK_Q05_A1_INTERCEPT}, ferrolearn {intercept}"
    );
}

/// Divergence: under `alpha=1.0` the intercept is quantile-dependent in
/// sklearn (`0.7387` at q=0.5 vs `2.7406` at q=0.8,
/// `sklearn/linear_model/_quantile.py:304`); ferrolearn returns an identical
/// ≈ 0.912 intercept for both quantiles.
/// Tracking: #332, #506.
#[test]
fn divergence_alpha1_intercept_quantile_dependent() {
    let (x, y) = oracle_dataset();
    let f08 = QuantileRegressor::<f64>::new()
        .with_quantile(0.8)
        .with_alpha(1.0)
        .with_max_iter(2000)
        .fit(&x, &y)
        .unwrap();
    let intercept = f08.intercept();
    assert!(
        (intercept - SK_Q08_A1_INTERCEPT).abs() < 1e-6,
        "q=0.8 alpha=1.0 intercept: sklearn {SK_Q08_A1_INTERCEPT}, ferrolearn {intercept}"
    );
    // The L1 sparse vertex also holds at q=0.8: coef is exactly [0,0,0].
    let coef = f08.coefficients();
    for (j, &sk) in SK_Q08_A1_COEF.iter().enumerate() {
        assert!(
            (coef[j] - sk).abs() < 1e-8,
            "q=0.8 alpha=1.0 coef[{j}] must be EXACTLY zero (LP vertex): \
             sklearn {sk}, ferrolearn {}",
            coef[j]
        );
    }
}

// ---------------------------------------------------------------------------
// Additional parity case (extra oracle, q=0.2 alpha=0.0): a non-median, no-
// penalty quantile. The LP solution must match sklearn's HiGHS coef_/intercept_
// to ~1e-4. Tracking: #340, #506.
// ---------------------------------------------------------------------------

/// Parity: `QuantileRegressor(quantile=0.2, alpha=0.0)` `coef_`/`intercept_`
/// match the live sklearn 1.5.2 HiGHS LP optimum (`_quantile.py:298-304`).
#[test]
fn parity_quantile_02_no_penalty() {
    let (x, y) = oracle_dataset();
    let fitted = QuantileRegressor::<f64>::new()
        .with_quantile(0.2)
        .with_alpha(0.0)
        .with_max_iter(20000)
        .fit(&x, &y)
        .unwrap();
    let coef = fitted.coefficients();
    for (j, &sk) in SK_Q02_A0_COEF.iter().enumerate() {
        assert!(
            (coef[j] - sk).abs() < 1e-4,
            "q=0.2 alpha=0.0 coef[{j}]: sklearn {sk}, ferrolearn {}",
            coef[j]
        );
    }
    let intercept = fitted.intercept();
    assert!(
        (intercept - SK_Q02_A0_INTERCEPT).abs() < 1e-4,
        "q=0.2 alpha=0.0 intercept: sklearn {SK_Q02_A0_INTERCEPT}, ferrolearn {intercept}"
    );
}

// ---------------------------------------------------------------------------
// Near-match regime characterization (NOT a divergence — documents where IRLS
// happens to land near the LP: median regression with no penalty).
// ---------------------------------------------------------------------------

/// Characterization: at `quantile=0.5, alpha=0.0` (median regression, no
/// penalty) ferrolearn's IRLS intercept lands NEAR sklearn's LP intercept
/// (`sklearn/linear_model/_quantile.py:304`, ≈ 0.3243). This isolates the
/// divergence to (a) non-median quantiles and (b) nonzero alpha. This test is
/// EXPECTED TO PASS at the documented ~0.03 tolerance and is the control for
/// the failing pins above — it is NOT ignored.
#[test]
fn near_match_median_no_penalty() {
    let (x, y) = oracle_dataset();
    let fitted = QuantileRegressor::<f64>::new()
        .with_quantile(0.5)
        .with_alpha(0.0)
        .with_max_iter(2000)
        .fit(&x, &y)
        .unwrap();
    let intercept = fitted.intercept();
    // Loose tolerance: IRLS only approximately coincides with the LP here.
    assert!(
        (intercept - SK_Q05_A0_INTERCEPT).abs() < 0.05,
        "q=0.5 alpha=0.0 intercept near-match: sklearn {SK_Q05_A0_INTERCEPT}, \
         ferrolearn {intercept}"
    );
}
