//! Divergence pins for `HuberRegressor::fit` against the live sklearn 1.5.2
//! oracle (`sklearn/linear_model/_huber.py`).
//!
//! sklearn jointly optimizes `[coef, intercept, scale]` with L-BFGS-B over
//! `_huber_loss_and_gradient` (`sklearn/linear_model/_huber.py:325`), where the
//! inlier/outlier split is `|y - Xw - c| > epsilon * sigma`
//! (`sklearn/linear_model/_huber.py:67`) and `sigma` is bounded strictly
//! positive (`sklearn/linear_model/_huber.py:323`). ferrolearn instead runs
//! IRLS reweighted ridge with **no scale parameter**, so its outlier band is a
//! raw `epsilon` (≈1.35) rather than `epsilon * scale` (≈0.11 on this data).
//!
//! Expected values are loaded from `tests/fixtures/huber_oracle.json`, which is
//! generated by calling sklearn 1.5.2 directly (NOT copied from ferrolearn).

use ferrolearn_core::traits::Fit;
use ferrolearn_linear::HuberRegressor;
use ndarray::{Array1, Array2};

/// Oracle fixture: data + sklearn 1.5.2 expected fitted attributes.
struct Oracle {
    x: Array2<f64>,
    y_outlier: Array1<f64>,
    y_clean: Array1<f64>,
    sk_outlier_coef: Vec<f64>,
    sk_outlier_intercept: f64,
    sk_outlier_scale: f64,
    sk_clean_coef: Vec<f64>,
    sk_clean_intercept: f64,
}

fn load_oracle() -> Oracle {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/huber_oracle.json"
    ))
    .expect("read huber_oracle.json fixture");
    let v: serde_json::Value = serde_json::from_str(&raw).expect("parse huber_oracle.json");

    let to_mat = |rows: &serde_json::Value| -> Array2<f64> {
        let rows = rows.as_array().unwrap();
        let n = rows.len();
        let m = rows[0].as_array().unwrap().len();
        let mut flat = Vec::with_capacity(n * m);
        for r in rows {
            for c in r.as_array().unwrap() {
                flat.push(c.as_f64().unwrap());
            }
        }
        Array2::from_shape_vec((n, m), flat).unwrap()
    };
    let to_vec = |arr: &serde_json::Value| -> Vec<f64> {
        arr.as_array()
            .unwrap()
            .iter()
            .map(|e| e.as_f64().unwrap())
            .collect()
    };

    Oracle {
        x: to_mat(&v["X"]),
        y_outlier: Array1::from(to_vec(&v["y_outlier"])),
        y_clean: Array1::from(to_vec(&v["y_clean"])),
        sk_outlier_coef: to_vec(&v["sklearn_outlier"]["coef"]),
        sk_outlier_intercept: v["sklearn_outlier"]["intercept"].as_f64().unwrap(),
        sk_outlier_scale: v["sklearn_outlier"]["scale"].as_f64().unwrap(),
        sk_clean_coef: to_vec(&v["sklearn_clean"]["coef"]),
        sk_clean_intercept: v["sklearn_clean"]["intercept"].as_f64().unwrap(),
    }
}

/// Divergence (PRIMARY, #495): `HuberRegressor::fit` diverges from
/// `sklearn/linear_model/_huber.py:325` on the outlier dataset.
///
/// Input: `X = RandomState(0).randn(50,3)`, `y = X@[1,2,-1] + 0.1*randn(50)`,
/// `y[:5] += 20`. Default `HuberRegressor` (epsilon=1.35, alpha=1e-4).
///
/// sklearn returns `coef_ ≈ [0.990, 1.980, -0.999]`, `intercept_ ≈ 0.0095`,
/// `scale_ ≈ 0.082`. ferrolearn's IRLS returns `coef ≈ [1.742, 2.357, -0.643]`,
/// `intercept ≈ 1.749` — coef[0] off by ~0.75, intercept off by ~1.74. This is
/// ALGORITHMIC (the IRLS band lacks `sigma`): raising `max_iter` cannot close
/// it. Root cause is the absent `scale_` (#496) — the outlier band is a fixed
/// `epsilon` instead of `epsilon * scale`.
///
/// Tracking: #495
#[test]
#[ignore = "divergence: HuberRegressor IRLS fit lacks joint scale, diverges from sklearn L-BFGS on outlier data; tracking #495"]
fn divergence_huber_fit_outlier_dataset() {
    let o = load_oracle();

    let fitted = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_outlier)
        .expect("fit on outlier data");

    let coef = ferrolearn_core::introspection::HasCoefficients::coefficients(&fitted);
    let intercept = ferrolearn_core::introspection::HasCoefficients::intercept(&fitted);

    for (i, &sk) in o.sk_outlier_coef.iter().enumerate() {
        assert!(
            (coef[i] - sk).abs() < 1e-3,
            "coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6} (diff {:.4})",
            coef[i],
            (coef[i] - sk).abs()
        );
    }
    assert!(
        (intercept - o.sk_outlier_intercept).abs() < 1e-3,
        "intercept: sklearn={:.6}, ferrolearn={intercept:.6} (diff {:.4})",
        o.sk_outlier_intercept,
        (intercept - o.sk_outlier_intercept).abs()
    );
}

/// Divergence (#495/#496): `HuberRegressor::fit` does not converge to sklearn's
/// fitted `coef_` even when `max_iter` is raised far beyond sklearn's count,
/// proving the gap is ALGORITHMIC (missing joint `scale`), not a convergence
/// tolerance gap. sklearn converges in `n_iter_ = 15`
/// (`sklearn/linear_model/_huber.py:342`); ferrolearn with `max_iter = 10000`
/// still does not match.
///
/// Tracking: #495
#[test]
#[ignore = "divergence: HuberRegressor IRLS does not reach sklearn fit at any max_iter (algorithmic, not convergence); tracking #495"]
fn divergence_huber_fit_not_convergence_max_iter() {
    let o = load_oracle();

    let fitted = HuberRegressor::<f64>::new()
        .with_max_iter(10_000)
        .with_tol(1e-12)
        .fit(&o.x, &o.y_outlier)
        .expect("fit on outlier data");

    let coef = ferrolearn_core::introspection::HasCoefficients::coefficients(&fitted);
    // coef[0] in particular is off by ~0.75 regardless of iteration budget.
    assert!(
        (coef[0] - o.sk_outlier_coef[0]).abs() < 1e-3,
        "coef[0] with max_iter=10000: sklearn={:.6}, ferrolearn={:.6} (diff {:.4}) \
         — unchanged from default max_iter, confirming algorithmic divergence",
        o.sk_outlier_coef[0],
        coef[0],
        (coef[0] - o.sk_outlier_coef[0]).abs()
    );
    // Pin the missing scale_ as the root cause (sklearn scale_ ≈ 0.082).
    assert!(
        o.sk_outlier_scale > 0.0 && o.sk_outlier_scale < 0.2,
        "fixture sanity: sklearn scale_ in (0,0.2)"
    );
}

/// Control (#495): on the CLEAN (no-outlier) dataset Huber ≈ OLS, so ferrolearn
/// is expected to match sklearn's `coef_`/`intercept_` within a loose tolerance.
/// This isolates the divergence to outlier handling (the scale band). Left
/// un-ignored: if it passes it confirms the regression locus; if it fails it is
/// itself a divergence to pin.
///
/// sklearn (clean): `coef_ ≈ [0.975, 1.983, -1.009]`, `intercept_ ≈ -0.006`.
#[test]
fn control_huber_fit_clean_dataset_matches_sklearn() {
    let o = load_oracle();

    let fitted = HuberRegressor::<f64>::new()
        .fit(&o.x, &o.y_clean)
        .expect("fit on clean data");

    let coef = ferrolearn_core::introspection::HasCoefficients::coefficients(&fitted);
    let intercept = ferrolearn_core::introspection::HasCoefficients::intercept(&fitted);

    // Loose tolerance: Huber with tiny noise should land near OLS / sklearn.
    for (i, &sk) in o.sk_clean_coef.iter().enumerate() {
        assert!(
            (coef[i] - sk).abs() < 5e-2,
            "clean coef[{i}]: sklearn={sk:.6}, ferrolearn={:.6} (diff {:.4})",
            coef[i],
            (coef[i] - sk).abs()
        );
    }
    assert!(
        (intercept - o.sk_clean_intercept).abs() < 5e-2,
        "clean intercept: sklearn={:.6}, ferrolearn={intercept:.6} (diff {:.4})",
        o.sk_clean_intercept,
        (intercept - o.sk_clean_intercept).abs()
    );
}
