//! Regression guard for the `optim/lbfgs.rs` `minimize`/`minimize_inner`
//! refactor (ferrolearn #499).
//!
//! The refactor extracted the optimizer loop into a private
//! `minimize_inner -> (Array1<F>, usize)` consumed by BOTH `minimize`
//! (logistic_regression.rs) and `minimize_reporting` (huber_regressor.rs). The
//! biggest regression risk is that the extraction silently altered the SOLUTION
//! VECTOR for either consumer (e.g. by changing a convergence check while adding
//! the iteration counter). These tests assert the fitted `coef_`/`intercept_`
//! still match the live sklearn 1.5.2 oracle, proving the refactor is
//! behavior-preserving for the solution.
//!
//! R-CHAR-3: every expected value below is generated by a LIVE sklearn 1.5.2
//! call (commands quoted in each test), NOT copied from ferrolearn.

use ferrolearn_core::introspection::HasCoefficients;
use ferrolearn_core::traits::Fit;
use ferrolearn_linear::LogisticRegression;
use ndarray::{Array1, Array2};

/// Deterministic binary dataset shared with the sklearn oracle below.
///
/// Reproduce with:
/// ```text
/// rng = np.random.RandomState(42)
/// X = rng.randn(60, 3)
/// logits = X @ [1.5,-2.0,0.7] + 0.4
/// y = (rng.rand(60) < 1/(1+np.exp(-logits))).astype(int)
/// ```
fn binary_dataset() -> (Array2<f64>, Array1<usize>) {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/logistic_lbfgs_oracle.json"
    ))
    .expect("read logistic_lbfgs_oracle.json fixture");
    let v: serde_json::Value = serde_json::from_str(&raw).expect("parse fixture");

    let rows = v["X"].as_array().unwrap();
    let n = rows.len();
    let m = rows[0].as_array().unwrap().len();
    let mut flat = Vec::with_capacity(n * m);
    for r in rows {
        for c in r.as_array().unwrap() {
            flat.push(c.as_f64().unwrap());
        }
    }
    let x = Array2::from_shape_vec((n, m), flat).unwrap();
    let y: Array1<usize> = v["y"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| e.as_u64().unwrap() as usize)
        .collect();
    (x, y)
}

/// Live sklearn 1.5.2 oracle:
/// `LogisticRegression(solver="lbfgs", penalty="l2", C=1.0,
///  fit_intercept=True, tol=1e-8, max_iter=1000).fit(X, y)`
/// `clf.coef_[0]` and `clf.intercept_[0]`.
fn sklearn_coef() -> [f64; 3] {
    [
        1.536_509_684_740_826_6,
        -2.063_676_443_062_694,
        0.794_697_676_397_700_2,
    ]
}
fn sklearn_intercept() -> f64 {
    0.219_240_218_724_439_88
}

/// REGRESSION (#499): the `minimize_inner` extraction must NOT change the
/// LogisticRegression solution vector. `coef_`/`intercept_` must still match
/// the live sklearn 1.5.2 lbfgs/L2 oracle. A drift here would mean the shared
/// optimizer refactor silently altered convergence semantics across every
/// estimator that uses `LbfgsOptimizer::minimize`.
#[test]
fn logistic_coef_unchanged_by_lbfgs_refactor() {
    let (x, y) = binary_dataset();
    let model = LogisticRegression::<f64>::new()
        .with_c(1.0)
        .with_tol(1e-8)
        .with_max_iter(1000);
    let fitted = model.fit(&x, &y).expect("logistic fit");

    let coef = HasCoefficients::coefficients(&fitted);
    let intercept = HasCoefficients::intercept(&fitted);

    let sk = sklearn_coef();
    for (i, &expected) in sk.iter().enumerate() {
        let got = coef[i];
        assert!(
            (got - expected).abs() < 1e-6,
            "coef[{i}] drifted from sklearn lbfgs oracle: ferrolearn={got}, sklearn={expected}"
        );
    }
    let exp_int = sklearn_intercept();
    assert!(
        (intercept - exp_int).abs() < 1e-6,
        "intercept drifted from sklearn lbfgs oracle: ferrolearn={intercept}, sklearn={exp_int}"
    );
}
