"""ferrolearn — scikit-learn compatible Rust ML models."""

# Original 12 estimators
from ferrolearn._regressors import ElasticNet, Lasso, LinearRegression, Ridge
from ferrolearn._classifiers import (
    DecisionTreeClassifier,
    GaussianNB,
    KNeighborsClassifier,
    LogisticRegression,
    RandomForestClassifier,
)
from ferrolearn._transformers import PCA, StandardScaler
from ferrolearn._clusterers import KMeans

# Phase-2 expansion (~40 more)
from ferrolearn._extras import (
    AdaBoostClassifier,
    AgglomerativeClustering,
    ARDRegression,
    BaggingClassifier,
    BayesianRidge,
    BernoulliNB,
    Binarizer,
    Birch,
    ComplementNB,
    DBSCAN,
    DecisionTreeRegressor,
    ExtraTreeClassifier,
    ExtraTreesClassifier,
    ExtraTreesRegressor,
    FactorAnalysis,
    FastICA,
    FeatureAgglomeration,
    GaussianMixture,
    GradientBoostingClassifier,
    GradientBoostingRegressor,
    HistGradientBoostingClassifier,
    HistGradientBoostingRegressor,
    HuberRegressor,
    IncrementalPCA,
    IsolationForest,
    KernelPCA,
    KernelRidge,
    KNeighborsRegressor,
    Lars,
    LassoLars,
    LinearSVC,
    MaxAbsScaler,
    MinMaxScaler,
    MiniBatchKMeans,
    MultinomialNB,
    NMF,
    NearestCentroid,
    Normalizer,
    Nystroem,
    OPTICS,
    OneHotEncoder,
    OrthogonalMatchingPursuit,
    PolynomialFeatures,
    PowerTransformer,
    QuadraticDiscriminantAnalysis,
    QuantileRegressor,
    QuantileTransformer,
    RANSACRegressor,
    RBFSampler,
    RandomForestRegressor,
    RidgeClassifier,
    RobustScaler,
    SparsePCA,
    TruncatedSVD,
)

__all__ = [
    # Original 12
    "LinearRegression",
    "Ridge",
    "Lasso",
    "ElasticNet",
    "LogisticRegression",
    "DecisionTreeClassifier",
    "RandomForestClassifier",
    "KNeighborsClassifier",
    "GaussianNB",
    "StandardScaler",
    "PCA",
    "KMeans",
    # Linear extras
    "BayesianRidge",
    "ARDRegression",
    "HuberRegressor",
    "QuantileRegressor",
    "OrthogonalMatchingPursuit",
    "Lars",
    "LassoLars",
    "RANSACRegressor",
    "RidgeClassifier",
    "LinearSVC",
    "QuadraticDiscriminantAnalysis",
    # Bayes extras
    "MultinomialNB",
    "BernoulliNB",
    "ComplementNB",
    # Tree extras
    "DecisionTreeRegressor",
    "RandomForestRegressor",
    "ExtraTreeClassifier",
    "ExtraTreesClassifier",
    "ExtraTreesRegressor",
    "AdaBoostClassifier",
    "GradientBoostingClassifier",
    "GradientBoostingRegressor",
    "HistGradientBoostingClassifier",
    "HistGradientBoostingRegressor",
    "BaggingClassifier",
    "IsolationForest",
    # Neighbors extras
    "KNeighborsRegressor",
    "NearestCentroid",
    # Cluster extras
    "MiniBatchKMeans",
    "DBSCAN",
    "AgglomerativeClustering",
    "Birch",
    "FeatureAgglomeration",
    "OPTICS",
    "GaussianMixture",
    # Decomp extras
    "IncrementalPCA",
    "TruncatedSVD",
    "FastICA",
    "NMF",
    "KernelPCA",
    "SparsePCA",
    "FactorAnalysis",
    # Preprocess extras
    "Binarizer",
    "Normalizer",
    "OneHotEncoder",
    "PolynomialFeatures",
    "MinMaxScaler",
    "MaxAbsScaler",
    "RobustScaler",
    "PowerTransformer",
    "QuantileTransformer",
    # Kernel extras
    "KernelRidge",
    "Nystroem",
    "RBFSampler",
]
