//! Full-grid bit-exact regression guard for the #2216 degree==0 gating fix.
//!
//! The #2216 fix gated the degree-1 seeding/counting at 4 sites in
//! `polynomial_features.rs` (`new`, `feature_combinations`, `num_output_columns`,
//! `generate_poly_features`) behind `degree >= 1` / `degree == 0`. The headline
//! risk is that a wrong gating boundary corrupts the SHIPPED degree>=1 value-math
//! (REQ-1). This test re-fuzzes the FULL grid
//! (n_features ∈ {1,2,3,4} × degree ∈ {0,1,2,3,4} × interaction_only × include_bias)
//! against the LIVE sklearn 1.5.2 oracle and asserts that
//! `PolynomialFeatures::fit_transform`, `powers_`, and `n_output_features_` match
//! BIT-EXACT (f64 `to_bits`, atol=0), mirroring
//! `sklearn/preprocessing/_polynomial.py:525-564` (value build),
//! `:362` (`n_output_features_`), and `:250-264` (`powers_`).
//!
//! Oracle values are loaded from `tests/poly_grid_oracle.json`, generated by the
//! live sklearn oracle (R-CHAR-3 — NOT copied from ferrolearn). X is passed in as
//! exact f64 bit patterns so the comparison is purely about the transformer math,
//! not decimal parsing.

use ferrolearn_core::traits::{Fit, Transform};
use ferrolearn_preprocess::polynomial_features::PolynomialFeatures;
use ndarray::Array2;
use serde_json::Value;

fn f64_from_bits(v: &Value) -> f64 {
    f64::from_bits(v.as_u64().expect("bit pattern u64"))
}

#[test]
fn divergence_polynomial_grid_no_regression() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/poly_grid_oracle.json"
    ))
    .expect("oracle json present");
    let cases: Vec<Value> = serde_json::from_str(&raw).expect("parse oracle json");
    assert!(!cases.is_empty(), "oracle has cases");

    let mut failures: Vec<String> = Vec::new();

    for case in &cases {
        let nf = case["nf"].as_u64().unwrap() as usize;
        let degree = case["degree"].as_u64().unwrap() as usize;
        let interaction_only = case["interaction_only"].as_bool().unwrap();
        let include_bias = case["include_bias"].as_bool().unwrap();

        // Rebuild X from exact f64 bit patterns (no decimal round-trip).
        let xbits = case["Xbits"].as_array().unwrap();
        let nrows = xbits.len();
        let mut x = Array2::<f64>::zeros((nrows, nf));
        for (i, row) in xbits.iter().enumerate() {
            for (j, v) in row.as_array().unwrap().iter().enumerate() {
                x[[i, j]] = f64_from_bits(v);
            }
        }

        let tag = format!(
            "nf={nf} degree={degree} interaction_only={interaction_only} include_bias={include_bias}"
        );

        let poly = match PolynomialFeatures::<f64>::new(degree, interaction_only, include_bias) {
            Ok(p) => p,
            Err(e) => {
                failures.push(format!("{tag}: new() unexpectedly Err: {e:?}"));
                continue;
            }
        };

        // Value math (stateless transform).
        let out = match poly.transform(&x) {
            Ok(o) => o,
            Err(e) => {
                failures.push(format!("{tag}: transform() Err: {e:?}"));
                continue;
            }
        };

        let out_bits = case["out_bits"].as_array().unwrap();
        let exp_rows = out_bits.len();
        let exp_cols = if exp_rows > 0 {
            out_bits[0].as_array().unwrap().len()
        } else {
            0
        };
        if out.shape() != [exp_rows, exp_cols] {
            failures.push(format!(
                "{tag}: shape {:?} != sklearn [{exp_rows},{exp_cols}]",
                out.shape()
            ));
            continue;
        }
        for (i, row) in out_bits.iter().enumerate() {
            for (j, v) in row.as_array().unwrap().iter().enumerate() {
                let expected_bits = v.as_u64().unwrap();
                let actual_bits = out[[i, j]].to_bits();
                if actual_bits != expected_bits {
                    failures.push(format!(
                        "{tag}: out[{i},{j}] bits {actual_bits:#x} != sklearn {expected_bits:#x} \
                         (ferro={} sklearn={})",
                        out[[i, j]],
                        f64::from_bits(expected_bits)
                    ));
                }
            }
        }

        // Fitted attributes.
        let fitted = poly.fit(&x, &()).expect("fit ok");
        let exp_n_out = case["n_out"].as_u64().unwrap() as usize;
        if fitted.n_output_features() != exp_n_out {
            failures.push(format!(
                "{tag}: n_output_features_ {} != sklearn {exp_n_out}",
                fitted.n_output_features()
            ));
        }
        let exp_powers = case["powers"].as_array().unwrap();
        let p = fitted.powers();
        if p.shape() != [exp_powers.len(), nf] {
            failures.push(format!(
                "{tag}: powers_ shape {:?} != sklearn [{},{nf}]",
                p.shape(),
                exp_powers.len()
            ));
        } else {
            for (i, row) in exp_powers.iter().enumerate() {
                for (j, v) in row.as_array().unwrap().iter().enumerate() {
                    let expected = v.as_u64().unwrap() as usize;
                    if p[[i, j]] != expected {
                        failures.push(format!(
                            "{tag}: powers_[{i},{j}] {} != sklearn {expected}",
                            p[[i, j]]
                        ));
                    }
                }
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{} grid divergences vs sklearn 1.5.2:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
