//! Divergence audit for `ferrolearn-preprocess/src/feature_scoring.rs`
//! (`f_classif`, `f_regression`, `chi2`) against scikit-learn 1.5.2
//! `sklearn/feature_selection/_univariate_selection.py`.
//!
//! Upstream cites:
//! - `f_oneway`        `_univariate_selection.py:43-117`
//! - `f_classif`       `_univariate_selection.py:127-173`
//! - `_chisquare`      `_univariate_selection.py:176-192`
//! - `chi2`            `_univariate_selection.py:202-288`
//! - `f_regression`    `_univariate_selection.py:405+`
//! - p-values: `scipy.special.fdtrc` (F survival) / `chdtrc` (chi2 survival).
//!
//! Oracle (sklearn 1.5.2 + scipy, LIVE) — full-precision values hard-coded per
//! R-CHAR-3. Generated by:
//! ```text
//! python3 -c "import numpy as np; from sklearn.feature_selection import f_classif, f_regression, chi2
//! X=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,1.],[2.,1.,9.],[5.,3.,2.],[8.,9.,4.]]); yc=np.array([0,0,1,1,2,2])
//! F,p=f_classif(X,yc); print(F.tolist()); print(p.tolist())
//! yr=np.array([1.5,2.,3.5,4.,5.5,6.]); Fr,pr=f_regression(X,yr); print(Fr.tolist()); print(pr.tolist())
//! Xp=np.array([[1.,0.,3.],[0.,2.,1.],[2.,1.,0.],[1.,3.,2.]]); yc2=np.array([0,1,0,1])
//! c,pc=chi2(Xp,yc2); print(c.tolist()); print(pc.tolist())"
//! ```

use ferrolearn_preprocess::feature_scoring::{chi2, f_classif, f_regression};
use ndarray::{Array1, Array2, array};

// ---------------------------------------------------------------------------
// Oracle constants (sklearn 1.5.2 / scipy — LIVE, hard-coded per R-CHAR-3)
// ---------------------------------------------------------------------------

// f_classif on X (6x3), yc=[0,0,1,1,2,2]
const FC_F: [f64; 3] = [1.1162790697674418, 0.2021276595744684, 0.16883116883116864];
const FC_P: [f64; 3] = [0.43412099354562095, 0.8272727041025375, 0.852154388371403];

// f_regression on X (6x3), yr=[1.5,2.,3.5,4.,5.5,6.]
const FR_F: [f64; 3] = [3.0178571428571415, 0.5779185322703944, 0.04359836656257508];
const FR_P: [f64; 3] = [0.1573525616579098, 0.48947182910680265, 0.8448046567707372];

// chi2 on Xp (4x3), yc2=[0,1,0,1]
const CHI2_STAT: [f64; 3] = [1.0, 2.6666666666666665, 0.0];
const CHI2_P: [f64; 3] = [0.31731050786291115, 0.10247043485974942, 1.0];

fn fixture_x() -> Array2<f64> {
    array![
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0],
        [7.0, 8.0, 1.0],
        [2.0, 1.0, 9.0],
        [5.0, 3.0, 2.0],
        [8.0, 9.0, 4.0]
    ]
}

fn fixture_yc() -> Array1<usize> {
    array![0, 0, 1, 1, 2, 2]
}

fn fixture_yr() -> Array1<f64> {
    array![1.5, 2.0, 3.5, 4.0, 5.5, 6.0]
}

fn fixture_xp() -> Array2<f64> {
    array![
        [1.0, 0.0, 3.0],
        [0.0, 2.0, 1.0],
        [2.0, 1.0, 0.0],
        [1.0, 3.0, 2.0]
    ]
}

fn fixture_yc2() -> Array1<usize> {
    array![0, 1, 0, 1]
}

// ===========================================================================
// DIV-1 (FIXABLE, REQ-4): F-distribution p-value parity — these FAIL.
//
// Root cause: `f_distribution_sf` -> hand-rolled `regularized_incomplete_beta`
// continued fraction (feature_scoring.rs:520-600) is broken. F<->beta mapping
// (feature_scoring.rs:392-409) is correct. Both `f_classif` and `f_regression`
// p-values share this broken path.
// ===========================================================================

/// Divergence: ferrolearn `f_classif` p-values diverge from
/// `sklearn/feature_selection/_univariate_selection.py:127-173`
/// (`f, prob = special.fdtrc(...)` via `f_oneway`) for the 6x3 fixture.
/// scipy returns [0.43412..., 0.82727..., 0.85215...];
/// ferrolearn returns ~[0.72216, ...] (off by ~0.29 on feature 0).
/// Tracking: #1416, blocker #1417
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn divergence_f_classif_pvalues() {
    let x = fixture_x();
    let y = fixture_yc();
    match f_classif(&x, &y) {
        Ok((_f, p)) => {
            for j in 0..3 {
                let diff = (p[j] - FC_P[j]).abs();
                assert!(
                    diff < 1e-6,
                    "f_classif p[{j}]: ferrolearn {} vs scipy {} (|diff|={diff})",
                    p[j],
                    FC_P[j]
                );
            }
        }
        Err(e) => assert!(false, "f_classif returned Err: {e}"),
    }
}

/// Divergence: ferrolearn `f_regression` p-values diverge from
/// `sklearn/feature_selection/_univariate_selection.py:405+`
/// (`p_values = stats.f.sf(F, 1, degrees_of_freedom)`) for the 6x3 fixture.
/// scipy returns [0.15735..., 0.48947..., 0.84480...];
/// ferrolearn returns ~[0.07989, ...] (off by ~0.078 on feature 0).
/// Same broken `f_distribution_sf` / `regularized_incomplete_beta` root cause.
/// Tracking: #1416, blocker #1417
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn divergence_f_regression_pvalues() {
    let x = fixture_x();
    let y = fixture_yr();
    match f_regression(&x, &y) {
        Ok((_f, p)) => {
            for j in 0..3 {
                let diff = (p[j] - FR_P[j]).abs();
                assert!(
                    diff < 1e-6,
                    "f_regression p[{j}]: ferrolearn {} vs scipy {} (|diff|={diff})",
                    p[j],
                    FR_P[j]
                );
            }
        }
        Err(e) => assert!(false, "f_regression returned Err: {e}"),
    }
}

/// Divergence DIV-1 bounding point: a moderately-significant feature
/// (p ~ 0.06), to bound the small/mid-p region of the broken F survival fn.
/// df = (2, 3), F ~ 8.379.
///
/// LIVE oracle (sklearn 1.5.2):
/// ```text
/// python3 -c "import numpy as np; from sklearn.feature_selection import f_classif
///  X=np.array([[1.],[2.],[3.],[4.5],[5.],[7.]]); y=np.array([0,0,1,1,2,2])
///  F,p=f_classif(X,y); print(F.tolist(),p.tolist())"
/// -> F=[8.379310344827587], p=[0.059162558373273645]
/// ```
/// ferrolearn returns ~0.05018 (off by ~0.009).
/// Tracking: #1416, blocker #1417
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn divergence_f_classif_pvalue_significant() {
    const SK_P_SIG: f64 = 0.059_162_558_373_273_645;
    let x = array![[1.0_f64], [2.0], [3.0], [4.5], [5.0], [7.0]];
    let y: Array1<usize> = array![0, 0, 1, 1, 2, 2];
    match f_classif(&x, &y) {
        Ok((_f, p)) => {
            let diff = (p[0] - SK_P_SIG).abs();
            assert!(
                diff < 1e-6,
                "f_classif significant p[0]: ferrolearn {} vs scipy {SK_P_SIG} (|diff|={diff})",
                p[0]
            );
        }
        Err(e) => assert!(false, "f_classif returned Err: {e}"),
    }
}

/// Divergence DIV-1 bounding point: a clearly non-significant feature
/// (large p-value), to bound the upper tail of the broken F survival fn.
/// df = (1, 4), F ~ 0.135.
///
/// LIVE oracle (sklearn 1.5.2):
/// ```text
/// python3 -c "import numpy as np; from sklearn.feature_selection import f_regression
///  X=np.array([[1.],[2.],[3.],[4.],[5.],[6.]]); y=np.array([5.,1.,6.,2.,5.,2.])
///  F,p=f_regression(X,y); print(F.tolist(),p.tolist())"
/// -> F=[0.1346153846153846], p=[0.7322792621972789]
/// ```
/// ferrolearn returns ~0.74668 (off by ~0.014).
/// Tracking: #1416, blocker #1417
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn divergence_f_regression_pvalue_nonsignificant() {
    const SK_P_NONSIG: f64 = 0.732_279_262_197_278_9;
    let x = array![[1.0_f64], [2.0], [3.0], [4.0], [5.0], [6.0]];
    let y: Array1<f64> = array![5.0, 1.0, 6.0, 2.0, 5.0, 2.0];
    match f_regression(&x, &y) {
        Ok((_f, p)) => {
            let diff = (p[0] - SK_P_NONSIG).abs();
            assert!(
                diff < 1e-6,
                "f_regression nonsig p[0]: ferrolearn {} vs scipy {SK_P_NONSIG} (|diff|={diff})",
                p[0]
            );
        }
        Err(e) => assert!(false, "f_regression returned Err: {e}"),
    }
}

// ===========================================================================
// GREEN-GUARDS — statistics + chi2 p-values match sklearn and MUST PASS.
// ===========================================================================

/// Green-guard: ferrolearn `f_classif` F-statistics match sklearn
/// `sklearn/feature_selection/_univariate_selection.py:127-173`
/// (`f_oneway` between/within mean-square ratio) exactly (tol 1e-9).
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn greenguard_f_classif_statistics() {
    let x = fixture_x();
    let y = fixture_yc();
    match f_classif(&x, &y) {
        Ok((f, _p)) => {
            for j in 0..3 {
                let diff = (f[j] - FC_F[j]).abs();
                assert!(
                    diff < 1e-9,
                    "f_classif F[{j}]: ferrolearn {} vs sklearn {} (|diff|={diff})",
                    f[j],
                    FC_F[j]
                );
            }
        }
        Err(e) => assert!(false, "f_classif returned Err: {e}"),
    }
}

/// Green-guard: ferrolearn `f_regression` F-statistics match sklearn
/// `sklearn/feature_selection/_univariate_selection.py:405+`
/// (`F = corr^2 / (1 - corr^2) * degrees_of_freedom`) exactly (tol 1e-9).
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn greenguard_f_regression_statistics() {
    let x = fixture_x();
    let y = fixture_yr();
    match f_regression(&x, &y) {
        Ok((f, _p)) => {
            for j in 0..3 {
                let diff = (f[j] - FR_F[j]).abs();
                assert!(
                    diff < 1e-9,
                    "f_regression F[{j}]: ferrolearn {} vs sklearn {} (|diff|={diff})",
                    f[j],
                    FR_F[j]
                );
            }
        }
        Err(e) => assert!(false, "f_regression returned Err: {e}"),
    }
}

/// Green-guard: ferrolearn `chi2` statistics match sklearn
/// `sklearn/feature_selection/_univariate_selection.py:202-288`
/// (`_chisquare` observed-vs-expected) exactly (tol 1e-9).
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn greenguard_chi2_statistics() {
    let x = fixture_xp();
    let y = fixture_yc2();
    match chi2(&x, &y) {
        Ok((stat, _p)) => {
            for j in 0..3 {
                let diff = (stat[j] - CHI2_STAT[j]).abs();
                assert!(
                    diff < 1e-9,
                    "chi2 stat[{j}]: ferrolearn {} vs sklearn {} (|diff|={diff})",
                    stat[j],
                    CHI2_STAT[j]
                );
            }
        }
        Err(e) => assert!(false, "chi2 returned Err: {e}"),
    }
}

/// Green-guard: ferrolearn `chi2` p-values match scipy `chdtrc`
/// (chi-squared survival, gamma-based) used by
/// `sklearn/feature_selection/_univariate_selection.py:176-192` (`_chisquare`)
/// (tol 1e-6). This path uses the gamma-based SF which IS correct.
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn greenguard_chi2_pvalues() {
    let x = fixture_xp();
    let y = fixture_yc2();
    match chi2(&x, &y) {
        Ok((_stat, p)) => {
            for j in 0..3 {
                let diff = (p[j] - CHI2_P[j]).abs();
                assert!(
                    diff < 1e-6,
                    "chi2 p[{j}]: ferrolearn {} vs scipy {} (|diff|={diff})",
                    p[j],
                    CHI2_P[j]
                );
            }
        }
        Err(e) => assert!(false, "chi2 returned Err: {e}"),
    }
}

// ---------------------------------------------------------------------------
// Error contracts (green-guards)
// ---------------------------------------------------------------------------

/// Green-guard: `f_classif` errors on zero samples.
#[test]
fn greenguard_f_classif_empty_err() {
    let x = Array2::<f64>::zeros((0, 2));
    let y: Array1<usize> = Array1::zeros(0);
    assert!(f_classif(&x, &y).is_err());
}

/// Green-guard: `f_classif` errors on y-length mismatch.
#[test]
fn greenguard_f_classif_shape_mismatch_err() {
    let x = array![[1.0_f64, 2.0], [3.0, 4.0]];
    let y: Array1<usize> = array![0, 1, 2];
    assert!(f_classif(&x, &y).is_err());
}

/// Green-guard: `f_classif` errors with fewer than 2 classes.
#[test]
fn greenguard_f_classif_single_class_err() {
    let x = array![[1.0_f64], [2.0], [3.0]];
    let y: Array1<usize> = array![0, 0, 0];
    assert!(f_classif(&x, &y).is_err());
}

/// Green-guard: `f_regression` errors with fewer than 3 samples.
#[test]
fn greenguard_f_regression_too_few_samples_err() {
    let x = array![[1.0_f64], [2.0]];
    let y: Array1<f64> = array![1.0, 2.0];
    assert!(f_regression(&x, &y).is_err());
}

/// Green-guard: `f_regression` errors on y-length mismatch.
#[test]
fn greenguard_f_regression_shape_mismatch_err() {
    let x = array![[1.0_f64], [2.0], [3.0]];
    let y: Array1<f64> = array![1.0, 2.0];
    assert!(f_regression(&x, &y).is_err());
}

/// Green-guard: `chi2` errors on a negative feature value.
#[test]
fn greenguard_chi2_negative_feature_err() {
    let x = array![[1.0_f64, -1.0], [0.0, 1.0]];
    let y: Array1<usize> = array![0, 1];
    assert!(chi2(&x, &y).is_err());
}

// ---------------------------------------------------------------------------
// f32 statistic path (green-guard)
// ---------------------------------------------------------------------------

/// Green-guard: `f_classif` F-statistics on the f32 path match the sklearn
/// oracle within f32 precision (tol 1e-4).
#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn greenguard_f_classif_statistics_f32() {
    let x: Array2<f32> = array![
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0],
        [7.0, 8.0, 1.0],
        [2.0, 1.0, 9.0],
        [5.0, 3.0, 2.0],
        [8.0, 9.0, 4.0]
    ];
    let y: Array1<usize> = array![0, 0, 1, 1, 2, 2];
    match f_classif(&x, &y) {
        Ok((f, _p)) => {
            for j in 0..3 {
                let diff = (f64::from(f[j]) - FC_F[j]).abs();
                assert!(
                    diff < 1e-4,
                    "f_classif f32 F[{j}]: ferrolearn {} vs sklearn {} (|diff|={diff})",
                    f[j],
                    FC_F[j]
                );
            }
        }
        Err(e) => assert!(false, "f_classif f32 returned Err: {e}"),
    }
}

// ===========================================================================
// BROAD F-DISTRIBUTION SF RE-AUDIT (post-fix #1416 / DIV-1 #1417).
//
// The rewritten `regularized_incomplete_beta` + `betacf` Lentz continued
// fraction (feature_scoring.rs:520-608) is the WHOLE F-distribution survival
// function for f_classif/f_regression. These probes exercise it across
// small-p (deep tail) / large-p / moderate-p and varied (df1, df2) regimes
// against the LIVE scipy/sklearn oracle (scipy 1.17.1 / sklearn 1.5.2).
//
// All expected p-values produced by:
//   from sklearn.feature_selection import f_classif, f_regression
//   import scipy.special as sp            # sp.fdtrc(df1,df2,F)
// and hard-coded full-precision per R-CHAR-3. The F-statistic itself is
// green-guarded above, so any p mismatch is purely the beta/SF path.
//
// abs tol 1e-6 for p >= 1e-4; relative tol 1e-6 for tiny tail p (< 1e-4).
// ===========================================================================

/// Assert ferrolearn p ~= scipy p: absolute 1e-6 normally, relative 1e-6 in
/// the deep tail where the absolute value is below 1e-4.
#[allow(
    clippy::assertions_on_constants,
    reason = "fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn assert_p_close(label: &str, ferro: f64, scipy: f64) {
    let ok = if scipy.abs() < 1e-4 {
        // relative tolerance in the deep tail
        let rel = (ferro - scipy).abs() / scipy.abs();
        rel < 1e-6
    } else {
        (ferro - scipy).abs() < 1e-6
    };
    assert!(
        ok,
        "{label}: ferrolearn p={ferro:e} vs scipy p={scipy:e} (|diff|={:e})",
        (ferro - scipy).abs()
    );
}

/// Re-audit: small-p (deep tail) f_classif, df1=1, df2=4.
/// scipy `f_classif` -> F=702.24999999998, p=1.2051915548673901e-05.
fn p_classif(x: Array2<f64>, y: Array1<usize>) -> f64 {
    match f_classif(&x, &y) {
        Ok((_f, p)) => p[0],
        Err(e) => {
            // surface error as an out-of-band value the asserts will reject
            eprintln!("f_classif Err: {e}");
            f64::NAN
        }
    }
}

fn p_regression(x: Array2<f64>, y: Array1<f64>) -> f64 {
    match f_regression(&x, &y) {
        Ok((_f, p)) => p[0],
        Err(e) => {
            eprintln!("f_regression Err: {e}");
            f64::NAN
        }
    }
}

#[test]
fn reaudit_fclassif_smallp_df1_1_df2_4() {
    const SK_P: f64 = 1.205_191_554_867_390_1e-5;
    let x = array![[1.0_f64], [2.0], [1.0], [18.0], [19.0], [20.0]];
    let y: Array1<usize> = array![0, 0, 0, 1, 1, 1];
    assert_p_close("fclassif df1=1 df2=4 smallp", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_smallp_df1_2_df2_3() {
    const SK_P: f64 = 7.003_559_211_766_89e-5;
    let x = array![[1.0_f64], [2.0], [10.0], [11.0], [30.0], [31.0]];
    let y: Array1<usize> = array![0, 0, 1, 1, 2, 2];
    assert_p_close("fclassif df1=2 df2=3 smallp", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_smallp_df1_4_df2_3() {
    const SK_P: f64 = 5.991_706_103_976_139_6e-5;
    let x = array![
        [1.0_f64],
        [2.0],
        [10.0],
        [11.0],
        [20.0],
        [30.0],
        [40.0],
        [41.0]
    ];
    let y: Array1<usize> = array![0, 0, 1, 1, 2, 3, 4, 4];
    assert_p_close("fclassif df1=4 df2=3 smallp", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_tinytail_df1_2_df2_48() {
    // Deep tail p ~ 1.16e-23 — exercises the SF far into the tail.
    const SK_P: f64 = 1.164_285_141_106_291_2e-23;
    let xs: Vec<f64> = (0..51).map(|i| i as f64).collect();
    let x = Array2::from_shape_vec((51, 1), xs).unwrap_or_else(|_| Array2::zeros((51, 1)));
    let yv: Vec<usize> = (0..51usize).map(|i| i / 17).collect();
    let y = Array1::from(yv);
    assert_p_close("fclassif df1=2 df2=48 tinytail", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_smallp_df1_4_df2_20() {
    const SK_P: f64 = 9.216_000_000_000_005e-7;
    let x = array![
        [1.0_f64],
        [2.0],
        [3.0],
        [4.0],
        [5.0],
        [3.0],
        [4.0],
        [5.0],
        [6.0],
        [7.0],
        [5.0],
        [6.0],
        [7.0],
        [8.0],
        [9.0],
        [7.0],
        [8.0],
        [9.0],
        [10.0],
        [11.0],
        [9.0],
        [10.0],
        [11.0],
        [12.0],
        [13.0]
    ];
    let y: Array1<usize> = array![
        0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4
    ];
    assert_p_close("fclassif df1=4 df2=20 smallp", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_midp_df1_2_df2_3() {
    const SK_P: f64 = 0.225_780_224_143_261_88;
    let x = array![[1.0_f64], [2.0], [3.0], [2.0], [3.0], [6.0]];
    let y: Array1<usize> = array![0, 0, 1, 1, 2, 2];
    assert_p_close("fclassif df1=2 df2=3 midp", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_phalf_df1_1_df2_4() {
    // p ~ 0.5032 — right in the middle of the distribution.
    const SK_P: f64 = 0.503_189_405_110_266;
    let x = array![[1.0_f64], [2.0], [3.0], [1.6], [2.6], [3.6]];
    let y: Array1<usize> = array![0, 0, 0, 1, 1, 1];
    assert_p_close("fclassif df1=1 df2=4 phalf", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_largep_df1_2_df2_3() {
    // Large p ~ 0.9878 (F ~ 0.012) — upper tail of the SF.
    const SK_P: f64 = 0.987_780_125_732_433_6;
    let x = array![[1.0_f64], [5.0], [2.0], [4.0], [3.0], [3.5]];
    let y: Array1<usize> = array![0, 0, 1, 1, 2, 2];
    assert_p_close("fclassif df1=2 df2=3 largep", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_largep_df1_2_df2_3_b() {
    const SK_P: f64 = 0.852_397_063_691_114_9;
    let x = array![[1.0_f64], [4.0], [2.0], [5.0], [3.0], [3.2]];
    let y: Array1<usize> = array![0, 0, 1, 1, 2, 2];
    assert_p_close("fclassif df1=2 df2=3 largep_b", p_classif(x, y), SK_P);
}

#[test]
fn reaudit_fclassif_df1_1_df2_18() {
    const SK_P: f64 = 6.437_702_721_969_637e-5;
    let x = array![
        [1.0_f64],
        [2.0],
        [3.0],
        [4.0],
        [5.0],
        [6.0],
        [7.0],
        [8.0],
        [9.0],
        [10.0],
        [8.0],
        [9.0],
        [10.0],
        [11.0],
        [12.0],
        [13.0],
        [14.0],
        [15.0],
        [16.0],
        [17.0]
    ];
    let y: Array1<usize> = array![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
    assert_p_close("fclassif df1=1 df2=18", p_classif(x, y), SK_P);
}

// --- f_regression: varied df2 (df1 always 1) ------------------------------

#[test]
fn reaudit_fregression_n5_df2_3() {
    const SK_P: f64 = 0.058_409_190_114_941_92;
    let x = array![[1.0_f64], [2.0], [3.0], [4.0], [6.0]];
    let y: Array1<f64> = array![2.0, 1.0, 4.0, 3.0, 6.0];
    assert_p_close("fregression n=5 df2=3", p_regression(x, y), SK_P);
}

#[test]
fn reaudit_fregression_n20_df2_18() {
    const SK_P: f64 = 3.536_432_002_083_884_7e-15;
    let x = array![
        [0.0_f64],
        [1.0],
        [2.0],
        [3.0],
        [4.0],
        [5.0],
        [6.0],
        [7.0],
        [8.0],
        [9.0],
        [10.0],
        [11.0],
        [12.0],
        [13.0],
        [14.0],
        [15.0],
        [16.0],
        [17.0],
        [18.0],
        [19.0]
    ];
    let y: Array1<f64> = array![
        2.0, 1.0, 4.0, 3.0, 6.0, 5.0, 8.0, 7.0, 10.0, 9.0, 12.0, 11.0, 14.0, 13.0, 16.0, 15.0,
        18.0, 17.0, 20.0, 19.0
    ];
    assert_p_close("fregression n=20 df2=18", p_regression(x, y), SK_P);
}

#[test]
fn reaudit_fregression_n50_df2_48_phalf() {
    // p ~ 0.5625, large df2 — exercises the SF with df1=1, df2=48.
    const SK_P: f64 = 0.562_481_016_285_450_8;
    let mut xs: Vec<f64> = Vec::with_capacity(50);
    let mut ys: Vec<f64> = Vec::with_capacity(50);
    for i in 0..50 {
        xs.push(i as f64);
        ys.push((i % 7) as f64);
    }
    let x = Array2::from_shape_vec((50, 1), xs).unwrap_or_else(|_| Array2::zeros((50, 1)));
    let y = Array1::from(ys);
    assert_p_close("fregression n=50 df2=48 phalf", p_regression(x, y), SK_P);
}

// --- chi2 extra df: 3-class -> df=2 (gamma-based SF) -----------------------

#[test]
#[allow(
    clippy::assertions_on_constants,
    reason = "error arm fails loudly without panic!/unwrap (anti-pattern gate)"
)]
fn reaudit_chi2_3class_df2_pvalues() {
    // scipy chdtrc(2, .) : feature0 p=0.19691167520419403, feature1 p=0.26359713811572677
    const SK_P0: f64 = 0.196_911_675_204_194_03;
    const SK_P1: f64 = 0.263_597_138_115_726_77;
    let x = array![
        [2.0_f64, 1.0],
        [0.0, 3.0],
        [1.0, 2.0],
        [3.0, 0.0],
        [2.0, 2.0],
        [0.0, 1.0]
    ];
    let y: Array1<usize> = array![0, 1, 2, 0, 1, 2];
    match chi2(&x, &y) {
        Ok((_c, p)) => {
            assert!(
                (p[0] - SK_P0).abs() < 1e-6,
                "chi2 df=2 p[0]: ferrolearn {} vs scipy {SK_P0}",
                p[0]
            );
            assert!(
                (p[1] - SK_P1).abs() < 1e-6,
                "chi2 df=2 p[1]: ferrolearn {} vs scipy {SK_P1}",
                p[1]
            );
        }
        Err(e) => assert!(false, "chi2 returned Err: {e}"),
    }
}
